### ISSUE TITLE
PSP Adrenaline Driver issue

### ISSUE THREAD

**Issue by kazum1kun** [jimbob4000/RetroFlow-Launcher#100]
Hello again, sorry for bombarding you with issues but I do like this launcher a lot and I want it to be as good as possible.

Anyways this apparently is a shelved old issue ( #59 ) but I ran into this issue today. I tested and at least two games don't work properly with the default Inferno driver. Ys I & II, for example, can launch but will crash when I select Ys I in the main screen. Switching to March33 fixed this issue. 

So I wonder if it's possible to have a game-specific driver option? Maybe inside the game details screen where one can switch between the three drivers. 

Thanks a bunch!

**Comment by jimbob4000** [comment]
Hi again,

The adrenaline launcher eboot is by Leecherman and is closed source so I don't have much control over it unfortunately. 

I looked into it again around a month ago. For the moment I'll close the issue, but will keep an eye out for a solution.

**Comment by kazum1kun** [comment]
Thanks for your response. I will look into the retroarch option.

**Comment by jimbob4000** [comment]
Sorry, I updated my comment, retroarch only runs ps1 games, so won't be much help with psp. 

If the lack of driver support is a dealbreaker, then you could try vita launcher as this gives the option to choose drivers.

**Comment by kazum1kun** [comment]
Right yeah. But anyways I do thank you for all the help and changes, I can just launch Adrenaline and run affected games there instead.

**Comment by jimbob4000** [comment]
@kazum1kun 

I had another look at changing the driver for Adrenaline games and found a solution.
You can try it out in the updated pre-release:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v5.0.2

Worth reading the release notes as there's more features added.
These are the two notes you need for setting Adrenaline drivers.

> - New 'Game Options Menu' - Access by pressing the triangle button on a game and the triangle button again to access options.
>- Adrenaline - You can now set the driver and bin file to execute on a game-by-game basis. Available in the Game Options Menu (don't forget to click 'Save' when changing settings).

**Comment by kazum1kun** [comment]
That's great, I will give it a try. Thanks for your work!
