### ISSUE TITLE
5.1.0 does not launch PSX titles

### ISSUE THREAD

**Issue by InsanePrimate** [jimbob4000/RetroFlow-Launcher#102]
Version 5.1.0 does not launch PSX eboot titles. When trying to launch a title, it instead boots into Adrenaline. (tested with some official eboots, FFX for example). 5.0.1 does successfully launch these PSX games! I did downgrade for now. Still, many nice new features in this new release. Keep it up! :-)

**Comment by jimbob4000** [comment]
Hi, thanks for reporting the issue.

I've released a fix which can be dowloaded here:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v5.1.1

Sorry for the inconvenience
