### ISSUE TITLE
Random crashes or reboot when i click on an emulator game

### ISSUE THREAD

**Issue by alfchk** [jimbob4000/RetroFlow-Launcher#104]
Hi

I encounter some problems, in fact, when I launch emulator games (it does not happen with psp or vita games).
randomly, every 10 to 20 game launches, vita freeze or reboot when i click on a game.

I first thought it was because I was using a 512go sd with thousands of games.
so I started from 0 on a 32go sd. with only neo geo pocket color fullset.  the problem have remain the same.
so I deleted all the games except one, which doesn't even have a cover. the problem have remain the same.

I have tried all versions from 3.6.1 (launcher v2) to 5.1.1 (launcher v3).
I have tried on vita v1 and v2.
I have tried to delete all the plugins one by one (i have let only:
*kernel storagemgr.sprx
*main henkaku.suprx
*NPSX10016 hankaku.suprx 
*NPSX10015 hankaku.suprx )
problem is always here.

(i'm with firmware: 3.65 "2 japanese caracters"-2)
have you any idea where does the problem come from?

**Comment by jimbob4000** [comment]
It's not something I have come across. 

What is the full filename of the last renaming game? (The one without the cover). 

Are you using custom directories?

Also if you open retroarch, does the game load?

Sorry for all the questions, I'm trying to narrow down some potential issues. 

Thanks

**Comment by alfchk** [comment]
Yes all games launch perfectly on retroarch. This problem occurs with any game, totally randomly. I run it a lot of times with retroflow and it works perfectly but sometimes it freezes or reboots directly when confirming the game. I can't run the same game 10 to 20 times without this happening

**Comment by jimbob4000** [comment]
Sorry, I'm not sure how to help on this one. 

I've not had any issues like this reported before, maybe try vita launcher for a while. 

If a problem occurs with that app too on occasion, maybe there's something else going on.

**Comment by alfchk** [comment]
Video showing the crash (it freezed twice). Randomly. Launching the same game that works fine. Sometimes it reboots. And I get this problem no matter the game I launch with retroarch on retroflow
https://files.fm/f/6nnu3d74x
(crash at 2min and then 4min50)

Same rom launch, in the same folder with vita launcher. (No crash nor reboot. Before making the video, I launched it 50 times and I had no problem)
https://files.fm/f/vrebsaavc

Video showing my firmware and the plugins
https://files.fm/f/scpqczfh8

**Comment by jimbob4000** [comment]
Hi, thanks for the videos.

I've updated the launch process to be closer to the vita launcher.

Please try this updated version to see if it's any better:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

Let me know how it goes.

Thanks

**Comment by alfchk** [comment]
Thanks. No more crashes, it is really great!
However, when I put from approximatively 2000 to 2500 roms and when I run a game, I get a message "would you like to quit retroflow ?" ,when launching retroarch.
When I put less roms I don't get this message. I don't know the exact number to get the message.
Do you have an idea to avoid this message ?
 Thanks

**Comment by jimbob4000** [comment]
No idea

**Comment by jimbob4000** [comment]
Sorry for the short reply. 
It's always been a bit of a mystery why it sometimes asks to close. 

You could try the nightly version:

https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

The launch commands are different there, and it include a close command, so may work better for you.

**Comment by alfchk** [comment]
Thanks.
I've already tested. I even tested all the Nightlys since then but the problem remain. I made a video here below, i hope it could maybe help you to understand.

https://files.fm/u/vtbmkkwnq?fbclid=IwAR2dv-z0j0t8lTFXe6_PSt9LmlfnYhkM0hLst1PfqB9Zw239HXgWcCerA7g#/view/ggvspm4g3

00m00s : Only MAME roms are there (1806 roms). launching MAME rom "005" with retroarch, no need to confirm to quit retroflow

00m35s : Adding Snes roms folder (785 roms)
01m30s : roms rescan
10m45s : launching snes rom "96 zenkok", confirmation needed to quit retroflow
11m00s : launching the same 005 MAME rom, confirmation needed to quit retroflow

11m15s : Deleting MAME rom folder from retroflow
11m50s : rescan
13m15s : launching the same snes rom "96 zenkoku", no need to confirm to quit retroflow

According to my tests, it doesn't come from the number of folders but from the number of roms. no matter the number of roms folders with roms inside, at Around 2500 roms  it asks for confirmation

**Comment by jimbob4000** [comment]
Thanks, the only thing I can think of is that the app is busy creating the list of games and filling in the covers. 

I'll take a look to see if there's a fix, but it may be a long shot.

**Comment by alfchk** [comment]
Before your updated launch process 3weeks ago who have corrected the crash problem, the confirmation to quit was not here

**Comment by jimbob4000** [comment]
It appears I can only fix one of your problems. 

There are two launch commands available to me using the Vita Lua. 

Option 1: The old launch command will work with over 2,000 games, but occasionally a game may fail to load. (Eboot command using repatch). 

Option 2: The new launch command is more reliable, but you will be prompted to close if you have a large library of games. (ExecuteUri command). 

I think I will revert back to using option 1 for the next nightly version. 

Sorry, it's a trade off I'm afraid.

**Comment by jimbob4000** [comment]
@alfchk ,

Good news, Rinnegatamante has kindly helped out with the issue, I think it's been resolved.

Please download the latest app from the nightly release:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

Thanks

**Comment by alfchk** [comment]
That work perfectly
Big thank
