### ISSUE TITLE
PSVSD + SD2Vita  = Failed Update \ Fresh Install

### ISSUE THREAD

**Issue by GrindLogic** [jimbob4000/RetroFlow-Launcher#107]
System:
===================
3G model
ux0 = PSVSD = OS + Apps + Vita Games
uma0 = SD2Vita = PSP + Retro Games

Description:
===================
Update or Install seems to be touchy with both PSVSD & SD2Vita active...don't recall this ever being an issue prior.

Notes
===================
PSVSD only & clean v5.1.1 install...scan took about a 20th the time it took compared to prior build when scanning only the PSVSD...maybe I should test older builds with the SD2Vita removed...maybe there is some odd hardware conflict going on.

Summary:
===================
PSVSD + SD2Vita  + v4.0.3 to v5.1.1 Update = Fail -- hang at startup
PSVSD + SD2Vita  + v5.1.1 to Nightly Update = Fail -- hang at startup
PSVSD + SD2Vita  + Fresh v5.1.1 Install = Fail -- hang at startup (Deleted RetroFlow from both App & Data)
PSVSD + Fresh v5.1.1 Install = Success -- Vita & Homebrew scan successful
PSVSD + SD2Vita  + v5.1.1 Installed + Rescan = Fail -- hang on rescan
PSVSD + SD2Vita  + v5.1.1 Installed + Download Art + Rescan = Success -- all games appear to present and all games with artwork appear to have them

**Comment by jimbob4000** [comment]
Hi, can you clarify what you mean by hang, or touchy?
Did you get any error codes, or did the loading bar freeze before 100%?

The method of scanning from v5 changed, so it's important to wait for it to complete, quitting halfway may cause issues.

I don't have a 3G or PSVSD, so can't really help test this, but it sound's like it's working based on the last line of your summary?

**Comment by GrindLogic** [comment]
Touchy in this context means hang.

No error codes....just splash screen then waiting for hell to freeze over.

I waited for nearly 24 hours...I'm going to be bold here and call that a hang.

With only using the PSVSD the scan was some where around 35min give or take. Plugging in the SD2Vita & doing Art Download was another 20min or so...then Rescan took about 35-45min which brought up the Retro and PSP stuff.

It's working...of a sort...it basically a work around.
Step 1. PSVSD only Install \ update RetroFlow
Step 2. PSVSD only Run RetroFlow allow first run scan to complete then exit (35min +\-)
Step 3. Plug in SD2Vita so now both PSVSD & SD2Vita are active
Step 4. Run RetroFlow then download all Artwork (20min +\-)
Step 5. Rescan games (35-45min +\-)
Step 6. Game on!

If I do the rescan prior to downloading the Artwork it appears to hang...granted I only waited 2hr before throwing up my arms and saying the hell with it....so maybe it would have completed at some point...not sure.

**Comment by jimbob4000** [comment]
When it's scanning for 30mins, is the progress bar moving? Or stuck at 100%?

If the app is that slow, to be honest I would downgrade to the last version that worked well for you. 

30 minutes is a long time, 24 hours is a sign that something is wrong and it should be quit. 

Can I ask how large your library is, and is it mainly psp/retro?

**Comment by GrindLogic** [comment]
on Step 2 progress bar moves as normal
Don't recall if there was one or not for Step 4 or Step 5

hmm once it's up and running its fine...it's just setup that is a pain...how ever even when doing the work around...it's faster in this version than in prior versions when doing everything at once for setup.

I know that the SD2Vita is faster than the PSVSD...I know someone was working on a driver for the PSVSD to speed things up...but at the time I was looking into it it was causing data errors.

Both interfaces have 1tb MicroSD's in them using large clusters...64k I think. The PSVSD has I think 870gb on it all Vita Games with a few Apps. the SD2Vita has just under 600gb being PSP & Retro.

I'll redo a clean install and see about getting you some hard numbers.

**Comment by jimbob4000** [comment]
I'm not really sure what to say, if it's faster than the previous version when the upgrade worked, then its a positive. 

2tb overall is a quite a lot, if it's taking 30 minutes to rescan each time your checking for new games, then you have more patience than me. 

I would pretty much written it off and used vita launcher instead. 

I don't think I'll be able to help on this, without a clear sign of an error or a reason for a slowdown, other than a large collection. 

The app isn't very efficient I'm afraid.

**Comment by GrindLogic** [comment]
Oh it certainly is a positive...the only down side is that prior versions for whatever reason allowed me to scan at setup both the PSVSD & SD2Vita at the same time...where now I have to use the work around.

Well when HexFlow originally came out...I did write it off...sexy as it was...the forced rescan upon each running of the app made it unusable.

However with RetroFlow only forcing scan on setup\update...I can grin and bear it....since I'm not swapping the SD2Vita out for a cartridge all the time.

Yeah my storage is slightly out of hand...I can't really recommend others doing what I did...but I do recommend folks getting a 1tb microSD and a SD2Vita.

**Comment by jimbob4000** [comment]
Sorry, what workaround?

I thought you said all your games are found across both partitions now you have setup and rescanned?

**Comment by BlackSheepBoy69** [comment]
I have roughly the same issue. 1tb about to upgrade to 1.5tb, all scans take insanely long, probably ~10 minutes. Basicly on a hardware level, the file system has a list file that says what all the contents are. Every time you run System.DoesFileExist(*name of file*), it goes through the whole list and checks each one as an "if" statement (note: you never see this. That's just how System.DoesFileExist() works)...

What you can do is load the entire chunk of the list with System.listdirectory(*name of folder*) and convert it to a switch statement and it can run in linear time (ex: in a few seconds or under a minute). For mine it's almost done, for RetroFlow it would take reworking a huge amount of the code. Give me a week or 2 and it will probably be ready and I'll reply back.

**Comment by BlackSheepBoy69** [comment]
If you're having trouble where you have to do this "workaround" which, as I understand it, is that you can't have it scan both your TB cards at once or it will crash, you could be straight up crashing the system by running out of RAM lol.

**Comment by GrindLogic** [comment]
Actually my workaround isn't contestant...it worked once....and not since then. :(

I've been banging away at this off and on trying to figure stuff out.

I actually went and gave bogus info on PSP & Retro stuff...basically everything that I have on my SD2Vita...so the only valid entries are for the Vita stuff on the PSVSD...and yet I see the activity light for the game cart being hammered.

I ordered up some v3 SD2Vita cards and a Samsung MicroSD...to test if this makes a difference as right now I'm running v6 SD2Vita & ScanDisk. It probably won't make a difference since VitaShell sees everything fine...but who knows.

I'll reply back once I have something looking consistent.

**Comment by jimbob4000** [comment]
Okay, I'll close the issue for now as this thread is far too long to make sense of, plus there's lots of unanswered questions. 

Raise a new issue once you're setup and have a better idea what's going on.

Blacksheeps upcoming app should be faster then mine, hopefully it may resolve some issues.

Retroflow is nearing end of life and I'm not really prepared to rewrite scanning for something I won't be able to test.
