### ISSUE TITLE
Error with games that include the "&" symbol in the game name

### ISSUE THREAD

**Issue by John3d** [jimbob4000/RetroFlow-Launcher#108]
Hi

When running a game from Retroflow to run with some retroarch core, if the game (rom) includes the "&" symbol in the name (for example: "Sonic & Knucles.zip") retroarch crashes when trying to load it.

**Comment by jimbob4000** [comment]
Hi, try the nightly build:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

Games with "&" are working for me, 'Joe & Mac', 'Mario & Luigi - Superstar Saga'.

Please also check if the game loads from within retroarch.

**Comment by John3d** [comment]
I installed the latest RetroFlow nigthly and it still doesn't work with the retroarch cores.

I tried to run a game with DeadaluX64 and it works.

**Comment by jimbob4000** [comment]
So a game with an '&' symbol works for DeadaluX64?

Can you open RetroArch and try loading 'Sonic & Knucles.zip' to see if it's a problem with your setup please?

Also please provide the full filename for one of the games that won't load, as they seem to be fine for me.

**Comment by John3d** [comment]
RetroFlow + DeadaluX64, works correctly

I've tried several games loading them directly from RetroArch and they work fine.

Some games tested:

Sonic & Knucles (World).md -----  core "Genesis Plus Gx (v1.7.4)"

Mario & Luigi - Superstar Saga (Europe)(En,Fr,De,Es,It).gba  ------  core "gpSP (v0.91)

Asterix & Obelix (Europe)(En,Fr,De,Es).sfc   --- core "Snes9x 2005 (v1.36)"

**Comment by jimbob4000** [comment]
I'll check again, just wondering if it's a retroarch version issue. 

Just out of curiosity, can you try vita launcher for those games that fail to load.

**Comment by John3d** [comment]
I just tested games with vita launcher and I have the same problem with games with that symbol.

**Comment by jimbob4000** [comment]
What version of retroarch are you running?

**Comment by John3d** [comment]
Last night I updated to the latest version with VitaDB Downloader.
Retroarch v.14.0 (Jan 28 2023)

**Comment by jimbob4000** [comment]
I just updated to the nightly on vitadb too and experienced the same issue.
It seems to be an issue with RetroArch.

You can try installing one of the stable builds rather than a nightly version.
Or you can install the same version I use: https://buildbot.libretro.com/stable/1.9.9/playstation/vita/

**Comment by John3d** [comment]
Thanks, I have been able to verify that in version 1.9.9 and version 1.10.0 it works correctly.
From version 1.11 onwards the error appears.
Error reported to Retroarch

**Comment by jimbob4000** [comment]
@alfchk this is an issue with retroarch
https://github.com/libretro/RetroArch/issues/14930
