### ISSUE TITLE
Showing the vita ports in app (GTA SA, Max Payne, Dead Space etc.)

### ISSUE THREAD

**Issue by disableai** [jimbob4000/RetroFlow-Launcher#110]
Hi, is there any way to make program show vita ports amongst common vita games in library? Right now it doesn't recognize them (except Return to Castle Wolfenstein port). Thank you.

**Comment by jimbob4000** [comment]
Yes, you can press triangle on a game and override the category to Vita

**Comment by disableai** [comment]
> Yes, you can press triangle on a game and override the category to Vita

but how would i do this, if those games (vita ports) dont show in the retroflow launcher?

**Comment by jimbob4000** [comment]
They will be in the homebrew category. 

If they aren't there, then rescan for new games and make sure the homebrew category is turned on.

**Comment by disableai** [comment]
> They will be in the homebrew category.
> 
> If they aren't there, then rescan for new games and make sure the homebrew category is turned on.

thank you very much, everything worked fine
