### ISSUE TITLE
Feature Request: Save last position

### ISSUE THREAD

**Issue by dni-coder** [jimbob4000/RetroFlow-Launcher#111]
Is it possible to implement a setting, so the retroflow launcher remember last position where a game was started and start at this position next launch.

Example:  you are at position 22 and start that game. Now you close this game and start again RetroFlow Launcher.
Normaly it will start again at position 1, but it would be nice to start at 22.

**Comment by jimbob4000** [comment]
Hi, you can change the startup category to recently played in the settings menu. When the app starts, the first game you see will be the one you played last.

**Comment by dni-coder** [comment]
Hello Jimbo,
I know this category, but it’s not what I mean.

my request would help, if you have a big library of games and you want to test the games, then you have to start always from the beginning to scroll.

**Comment by jimbob4000** [comment]
Okay, makes sense. 

I don't think it's something I'd like to add, it's come up before. 

It may be in an upcoming version of HexFlow custom.
