### ISSUE TITLE
An error occurred after downloading game covers and backgrounds

### ISSUE THREAD

**Issue by Husky363** [jimbob4000/RetroFlow-Launcher#112]
after successfully downloading game covers and background covers an error has occurred as follows in a text that prevents me booting retro flow launcher 

here's the error text :

Ux0:/data/retroflow/titles/fba_2012.lua:2 "j" expected near discor 94

press x to restart
press o to enable/disable ftp

**Comment by jimbob4000** [comment]
One of the fba games is causing the error, if you can send me the fba lua file I can take a look in a few days. 

Or if you open the lua file you may be able to find the problem game by searching for the discor text in the error code. 

Delete that game from the fba rom directory, also delete the fba lua file and the app should work again.

**Comment by Husky363** [comment]
thank you very much for your reply. i tried it on another vita and now it gives me another error says

cannot open ux0:/app/retroflow/script.lua: not owner

**Comment by jimbob4000** [comment]
Reinstall the vpk file, it sounds like you may have deleted something else by accident.

**Comment by jimbob4000** [comment]
Hi @Husky363 

I think I found the problem related to the FBA issue.

Please delete these folders:

`ux0:/data/RetroFlow/CACHE`
`ux0:/data/RetroFlow/DATABASES`
`ux0:/data/RetroFlow/TITLES`

Then install the vpk from the nightly build: https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

Thanks
