### ISSUE TITLE
"C1-2738-0" error when launching atari 5200 rom

### ISSUE THREAD

**Issue by alfchk** [jimbob4000/RetroFlow-Launcher#113]
hi

"C1-2738-0" error when launching atari 5200 rom (same error for all roms)

**Comment by jimbob4000** [comment]
When you say all roms, presumably you mean only atari 5200?

It's working fine for me.

Please check if the games work within retroarch, and you have setup the core properly with bios and compatible games.
https://docs.libretro.com/library/atari800/

Also check you have the core installed:
`ux0:/app/RETROVITA/atari800_libretro.self`

**Comment by alfchk** [comment]
Hi

Yes i mean all atari 5200 roms.
They work perfectly directly in retroarch.
(In the past they work in retroflow too)
But I have "a5200_libretro.self" but not "atari800_libretro.self" in "ux0:/app/RETROVITA/"

**Comment by jimbob4000** [comment]
Okay, there's the problem.
Not sure why it wouldn't be there, it's still part of the current retroarch builds.

I've attached the file you need, extract it to the `ux0:/app/RETROVITA/`folder and you should be good to go.

[atari800_libretro.self.zip](https://github.com/jimbob4000/RetroFlow-Launcher/files/10833255/atari800_libretro.self.zip)

**Comment by alfchk** [comment]
thank you ;)

**Comment by alfchk** [comment]
i dont understand why, but with atari800 emulator, when i launch game, emulator boot to memopad (like no game was launch). but with a5200_libretro.self games work fine. (i have all bios in the good directory with good checksums)

(and mednafen_pce_libretro.self is better for PCE because mednafen_pce_fast_libretro dont run supergrafx games)

**Comment by alfchk** [comment]
(i have updated last nightly retroarch and retroflow)

**Comment by alfchk** [comment]
Ok thanks

**Comment by jimbob4000** [comment]
@alfchk 

'mednafen_pce_fast_libretro.self' runs faster, 'mednafen_pce_fast_libretro' seems slow with audio bugs.
There's only 6 SuperGrafx games, if it gets added as a new category, it would be a very low priority.

**Comment by alfchk** [comment]
Ok i understand
I already have change them in index.lua but I will prefer your méthod with override retroarch.
Thanks again for your reactivity
