### ISSUE TITLE
Request for translation review for upcoming v6 release

### ISSUE THREAD

**Issue by jimbob4000** [jimbob4000/RetroFlow-Launcher#114]
Hi @dagadtwok, @SK00RUPA and @kuragehimekurara1,

Thanks so much for your contributions with translations so far, it really is appreciated.

There's a new v6 release around the corner where you can create new categories (Collections) and add games to your own games to them.

I've added (google) translations for new text and was wondering if you would like any changes made before the release (in the next few days).

Updated translations are below:

- Hungarian: https://github.com/jimbob4000/RetroFlow-Launcher/commit/38aa4def729f601d19f149a6e8ded2068ef6d065
- Polish: https://github.com/jimbob4000/RetroFlow-Launcher/commit/5c98329c57ac40942c6f84778d380965b258a908
- Japanese, Ryukyuan, Chinese Traditional and Simplified: https://github.com/jimbob4000/RetroFlow-Launcher/commit/48d14aa2c530b5376ad60a881b9d45f1a6f63c36

You can try out the pre-release if you would like to see it in context:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

How to create a collection:

- Press the triangle button on a game and press the triangle button again to bring up the mini menu, then select 'Add to collection'.

Renaming or deleting a collection:

- Collections can be renamed/deleted by going to the main settings menu 'Other settings > Edit collections'.

If you can let me know if you're able to review, it would be great.
Likewise it's perfectly okay to say 'I don't think I will have time', I won't be offended at all.

Thanks again

**Comment by BlackSheepBoy69** [comment]
"There's a new v6 release around the corner"

If you turn around and make the nightly into a v6 the changelog will be huge XD

Nothing wrong with that though, great work and collections is cool!

**Comment by dariofflima** [comment]
The Brazilian Portuguese translation has many errors, I can help correct it.

**Comment by jimbob4000** [comment]
@dariofflima , if you don't mind, that would be awesome!

The Portuguese language file is saved here:
https://github.com/jimbob4000/RetroFlow-Launcher/blob/main/src/translations/PT.lua

**Comment by dariofflima** [comment]
> @dariofflima , if you don't mind, that would be awesome!
> 
> The Portuguese language file is saved here: https://github.com/jimbob4000/RetroFlow-Launcher/blob/main/src/translations/PT.lua

Just finished fixing the translation errors. I just wanted to point out that I translated it into Brazilian Portuguese, which is a little different from European Portuguese.

**Comment by BlackSheepBoy69** [comment]
Brazilian Portugese should be set as a new language file, then if RetroFlow auto-identifies your system as having "Brazilian Portugese" set as the system language, it'll go there (They are different enough that the Vita has 2 options for Brazilian in Language settings)

**Comment by jimbob4000** [comment]
Thanks @dariofflima and @BlackSheepBoy69. 

Blacksheep is right, I'll need to add Brazilian Portuguese as a new language which isn't a problem.

**Comment by dariofflima** [comment]
@jimbob4000 here is the brazilian portuguese translation file:

https://github.com/dariofflima/RetroFlow-Launcher/blob/main/src/translations/PT-BR.lua

**Comment by jimbob4000** [comment]
@dariofflima this is great, thanks for your help.

I've added it to the nightly build:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

I've also alphabetised the order of the languages, you will find it after Polish in the language settings.

Thanks again

**Comment by jimbob4000** [comment]
Hi everyone,

I added a new feature today called 'Smooth Scrolling', which makes the cover movements really smooth when browsing games. (Thanks to Axce)

I've added translations for it, but let me know if you would like one changed.

- English: `Smooth Scrolling: `
- Hungarian: `Sima Görgetés:`
- Polish: `Rolagem suave: `
- Japanese: `スムーズなスクロール：`
- Japanese Ryukyuan: `スムーズなスクロール：`
- Chinese Traditional: `平滑滾動 : `
- Chinese Simplified: `平滑滚动 : `
- Portuguese (Portugal): `Rolagem suave: `
- Portuguese (Brazil): `Rolagem suave: `

**Comment by SK00RUPA** [comment]
Hi! Polish translation is good to go.

Cheers!

**Comment by jimbob4000** [comment]
v6 is out, thanks for your help everyone.
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v6.0.0
