### ISSUE TITLE
corrupted PSP game causes scan to be really slow

### ISSUE THREAD

**Issue by GrindLogic** [jimbob4000/RetroFlow-Launcher#117]
Okay figured out what the issue was basically...and it wasn't hardware.

It seems it was a corrupted PSP game NPUG80293 other wise known as "Buzz! Quiz World".

Anyways the original reaction needs to be resolved...even if the cause of that reaction has been removed.

In case you forgot that was the hammering of my SD2Vita.

I can only assume...that RetroFlow couldn't find a file\read a file...and got caught up in a loop...with no condition to jump out of it and report an error...then continue on.

**Comment by jimbob4000** [comment]
Can you send me the corrupted file so I can check, please?

I've tested with that game and also a text file with the extension renamed to '.iso' and found no issue.

**Comment by jimbob4000** [comment]
Seconds thoughts, probably best not to send the file due to copyright. 

You could maybe send the .sfo file from within the iso. 

That's where retroflow gets the game info. 

Are you sure that game is the issue?
It consistently causes an error?

**Comment by GrindLogic** [comment]
It's a digital games...also it's junk data right now as is...but nuke the link afterwards.
https://www.mediafire.com/file/qbik78nqi5e9tzq/NPUG80293.rar/file

**Comment by jimbob4000** [comment]
I've updated the nightly to fix the issue.
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

The scan does hang for a while at the end of scanning titles, but nothing like before.
It's the best I can do as the sheer amount of files in the corrupt game's folder is difficult to handle.

Thanks for reporting, I feel it's an edge case, but on the plus side, the scanning should be slightly improved.
