### ISSUE TITLE
Failed to extract PSP Background

### ISSUE THREAD

**Issue by GrindLogic** [jimbob4000/RetroFlow-Launcher#118]
artwork\extract psp backgrounds
Error Code: C2-12828-1
ux0:data/psp2core-1679006886-0x000129e03-launch_scan.bin.psp2dmp

Dang to bad RAR or 7zip isn't supported the dump file came in at less than 10kb

[psp2core-1679006886-0x0001292e03-launch_scan.bin.zip](https://github.com/jimbob4000/RetroFlow-Launcher/files/10997709/psp2core-1679006886-0x0001292e03-launch_scan.bin.zip)

**Comment by GrindLogic** [comment]
hmm same error dealing with Vita Backgrounds.
[psp2core-1679025781-0x001cbf351d-launch_copy_vita_images.bin.psp2dmp.zip](https://github.com/jimbob4000/RetroFlow-Launcher/files/10997799/psp2core-1679025781-0x001cbf351d-launch_copy_vita_images.bin.psp2dmp.zip)

**Comment by jimbob4000** [comment]
I don't know how to analyse those dump files. 

Try installing and running copyicons to see if you get an error when running that. 

https://github.com/cy33hc/copyicons

**Comment by GrindLogic** [comment]
Okay with current nightly PSP...only the same 177 backgounds are extracted, it will not proceed to process any others.

Restarting retroflow or the Vita doesn't matter.

Rerunning the scan causes no issues until a background is downloaded manually.

The manual download image has no apparent issue.

Removing the manual image prevents the error.

It is clear the manual image is tripping the error...I created & removed images in different places in the game list...and dependent on where in the list it was created...would then correspond to when the error would be tripped.

It should be noted that when doing the batch PSP backgrounds...the first 177 backgrounds are displayed during the batch...then it's a blank screen from then on out...and proceeds much faster...hehe clearly since it's not doing any work at that time.

I'll get back to you about CopyIcons & rolling back to v5.1.1

**Comment by jimbob4000** [comment]
Okay, can you zip up the bad image and send it to me?

Needs to be in a zip file so I know GitHub doesn't alter it.

**Comment by GrindLogic** [comment]
Okay there does seem to be a resolution difference.

Common Dumped Images
480x272x8 8? 8bit color?

Error Downloaded Image
426x240x8

hmm I get that some don't have images embedded in them...but I'm hitting really low percentage here...and so far only games 0-F are being dumped...G+ nothing.
[ULUS10435.zip](https://github.com/jimbob4000/RetroFlow-Launcher/files/11004652/ULUS10435.zip)

**Comment by GrindLogic** [comment]
Okay ran CopyIcons...no error and Icon0.png & pic0.png seem to present in ux0:/apppmeta/??????/

Granted for whatever reason I can't see these folders & files when I mount ux0 via USB...and VitaShell denotes them in Pink or magenta...whatever.

Also moving the files to root doesn't make them appear when mounted...so I guess they have some flag on them to be hidden.

**Comment by jimbob4000** [comment]
Copyicons copies the files to ur0:/apppmeta/TITLEID

The image you sent seems to load fine

**Comment by jimbob4000** [comment]
For psp, I think the vita may be running out of memory, loading the images to display them.
I've turned off the display of the images in the attached vpk.
You should get past the letter G now.

For copying vita backgrounds I've removed some functionality to see if it helps.

I haven't added it to nightly, will update if it fixes something.
[2023-03-17-RetroFlow-kodiak-1.zip](https://github.com/jimbob4000/RetroFlow-Launcher/files/11006083/2023-03-17-RetroFlow-kodiak-1.zip)

**Comment by GrindLogic** [comment]
First run PSP still only extracted 177 out of 192 processed...which is still very short of 710 PSP games installed.

G-Force does have a background but "G.I. JOE(TM) The Rise of Cobra(TM)" didn't.

However second run it quickly sped through the games already extracted...then started extracting more games up to 51% (381)...then stopped extracting and sped through the rest without extraction.

Third run zipped to 51% done...so the start of N's...then started extracting backgrounds again....till it hit 78% (564) near the end of the S's...then just sped through till the end..without extraction.

Forth run shot through first 79% in no time flat then started extracting again, till it finally completed.

Okay it should be noted that the first run ended extractions...the same place as the prior versions...however in this version I can continue on....where the prior versions I was limited to the first 192 games and that was it.

So far as I can say the display of images didn't necessarily make a difference....other than I was able to continue on in further runs.

So if images are only shown for newly extracted games...and not existing extracted games...things might work fine.

I manually downloaded a background for "Archer Maclean's Mercury" then reran the background scan....and no errors. YAY!!

So PSP is in much better shape now. (671 / 710)

Not sure if you want to try and figure out why it doesn't extract everything in one go...or if you want to work in conditional image display.

I'll get back to you on Vita in a bit...over all very promising . :)

**Comment by jimbob4000** [comment]
Adding image display will probably cause the crash again. 

If an image is in the background directory, the extraction of the game is skipped. 

The image extraction works by getting the image from within the iso file. 

Can you delete or rename the psp background image folder in the retroflow folder please and see bar far it gets in one run?

I would test but I don't have that many games. Thanks

**Comment by GrindLogic** [comment]
Okay renamed PSP background folder...redid PSP background scan...and thumbed the hell out of the joystick. :)

Still only 177 images out of 192 games...which was 25-26% bar progress.

Something is tripping things up at that point. It didn't go to sleep...but yeah it runs long enough that if not attended it would in deed sleep.

I see all the names fly by...so it's not like the array or whatever you are using is getting stalled or trimmed...at least I don't think so...maybe do a debug build that lists the ISO & it's path...hmm actually maybe just have it create a TXT file that lists what is happening\when during the scan.

Is there anyway you could toss in a readout for memory pressure in the debug build.

it just seems odd that with or without image display things still come to a stop at the same point....granted now I can continue on...and I can manually add an image without things going bang.

**Comment by GrindLogic** [comment]
Okay Vita...Icon0.png & pic0.png are being copied.

Didn't notice any extractions...but really there shouldn't have been.

Now maybe there are some odd buffer issues going on...but it looks like pic0.png is being copied 2-3 times.

**Comment by jimbob4000** [comment]
**For PSP extraction** 

I managed to replicate the skipping problem.

It appears that the image within the iso is not being found after checking around 150 games.

This appears to be a bug with onelua, as it's closed source I don't think I will be able to fix the issue.
Unfortunately, the extraction will just need to be run multiple times.


**For Vita extraction** 

The background image and icon should be copied once to the RetroFlow folder.

Icons are saved here: `ux0:/data/RetroFlow/ICONS/Sony - PlayStation Vita`
Backgrounds are saved here: `ux0:/data/RetroFlow/BACKGROUNDS/Sony - PlayStation Vita`

Can you describe the buffer and multiple copy issue in more detail please?


P.S. I appreciate your help and patience on this, it's helping to resolve issues before the release

**Comment by GrindLogic** [comment]
OneLua seems to have a bit of a pulse here on GitHub...he\they seem to have a fair amount of stuff opened up...maybe they will share the code...or maybe fix the issue once they are made aware of it.

Vita...well the buffer...is just me referencing the console being written to...as I'm not sure if a string variable is being called twice or more.

Loose example:
Looking for Icon 23
Copying Icon 23 to ./././23.png
Copying Background 23 to ./././23.png
Copying Background 23 to ./././23.png
Looking for Icon 24
Copying Icon 24 to ./././24.png
Copying Background 24 to ./././24.png
Copying Background 24 to ./././24.png
Copying Background 24 to ./././24.png
...
So on and so forth...that is not exactly what it reads in the console...but close to it.

So it could be a string variable being called 2 or more times to print to the console...or it could actually be copying a file 2 or more times.

Note this is only being seen with the background and hasn't been seen with Icon.

No problem with the trouble shooting...it helps both of us...you get a project you are proud of...I get a new shiny. :)

**Comment by GrindLogic** [comment]
Is there no way to fiddle with the vita code from nightly...or is it an all or nothing kind of thing?

We really didn't fuss with it...just walked away.

I'll rerun CopyIcon and see if this behavior is present there as well....I don't recall seeing it...but I also wasn't looking for it.

**Comment by jimbob4000** [comment]
For vita extract it's just printing the activity, no duplicates, so all good. 

For psp, there's not much I can control with onelua, couldn't see where to post an issue as the GitHub just are releases based on the lua interpreter which is closed. 

Think this may be as good as it gets.

**Comment by GrindLogic** [comment]
Well if Vita isn't creating dups...then changing it's output to look more like what the PSP does would be nice.

If for the PSP we can't do every thing in one instance...can multiple instances be strung together?

off topic...but I just realized that my prior post about the corrupt PSP game...was flawed...the game was fine...that folder was it's DLC...doh! I'm guessing you figured that out and didn't point out that I was being a dumbass. :) Granted that folder was still the cause of things going side ways.

**Comment by jimbob4000** [comment]
The dlc thing is okay, others may make the same mistake. 

For psp stringing multiple instances doesn't work unfortunately, I tried it when testing today. 

For vita extract, I'll have a look inti it, but it's coded in C+ which is new to me.

**Comment by jimbob4000** [comment]
I've added the fixes we worked on into the nightly build.
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

When it comes to the v6 release, I'll add a new known issue about needing to run extract PSP again if you have a large library of PSP games.

Closing the issue for now
