### ISSUE TITLE
Loading time 3 Minutes for 5000 Games

### ISSUE THREAD

**Issue by ArchfiendNZ** [jimbob4000/RetroFlow-Launcher#12]
I have approximately 5000 games across multiple systems loaded onto my Vita and when first opening the RetroFlow Launcher it takes around three minutes to load (I timed it)

Is there Any room for optimization for those of us with larger libraries?

Thanks,
Arch

**Comment by jimbob4000** [comment]
Of the 5,000 games, is it mostly Vita?

**Comment by ArchfiendNZ** [comment]
Less than 10 vita games, mostly old retro titles (NES/SNES/GG/MS/MD, etc)

**Comment by ArchfiendNZ** [comment]
.

**Comment by jimbob4000** [comment]
I've released a new version with resolves the issue:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.0
