### ISSUE TITLE
Disabling the "Homebrew" category also causes homebrew apps to disappear from Collections.

### ISSUE THREAD

**Issue by dariofflima** [jimbob4000/RetroFlow-Launcher#121]
If you set the "Homebrew" category to "off" in the options menu, all homebrew that are also in collections disappear. I imagine this would not be the desired behavior.

**Comment by jimbob4000** [comment]
I can see where you're coming from on this one.

I've tried some quick fixes but they had some nasty complications.
I'll need to sit on this issue for a while to see if I can figure something out which doesn't involve a major change.

**Comment by jimbob4000** [comment]
@dariofflima 

I think the issue has been fixed, you can try it out on the nightly build:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

If a homebrew app is in a collection it now shows in collections, favorites, recent and the all category, regardless of whether the show homebrew setting is off.

P.S. if you had a chance to send over the Portuguese Brazilian language file, I'll add that to the app too, thanks.
