### ISSUE TITLE
Crash when pressing Circle too much

### ISSUE THREAD

**Issue by Axce** [jimbob4000/RetroFlow-Launcher#125]
Hello!

**When** I switch the view type by pressing Circle too many times, it crashes with this error :
```
An error occurred:
[string "?"]:1269: attempt to index global 'file_settings' (a nil value)

Press X to restart.
Press O to enable/disable FTP.
```

It crashes when i've switched the view type exactly 59 times.
It's consistent, and I can switch covers and categories between the Circle presses, it will always be 59 total.

It might crash sooner if I access the settings or the Triangle menu.

**Comment by jimbob4000** [comment]
Hi again, that bug has been annoying me for some time.

I think I've fixed it in the nightly build:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

**Comment by Axce** [comment]
Works for me!
