### ISSUE TITLE
RetroFlow Adrenaline Booter : Problem with PSP launching another executable

### ISSUE THREAD

**Issue by PukeGX** [jimbob4000/RetroFlow-Launcher#126]
Hello, 
First thanks for your Work, RetroFlow is great.

But I have a problem and I think it's an issue with PSP games that launch another .bin : especially with Castlevania Dracula X Chronicles (ULES00841) and Crazy Taxi Fare Wars (ULES00811) (maybe the problem is the same with Power Stone Collection, and the Capcom Classics...)

There is strange behavior in comparison with Adrenaline (of course, I use ISO for theses game)  :

- **When launching directly from Adrenaline**, they work fine with INFERNO driver, the Original game Symphony of the Night in Castlevania Dracula X Chronicles is working without problem ; NP9660 driver does not work correctly with theses games.

- **When Launching from RetroFlow Adrenaline Booter, with INFERNO or MACH33 driver**, when you try to launch an original games in Castlevania or a game in Crazy Taxi Fare Wares, it move you to the PSP startup, but then if you want to exit the PSP mode, all the Vita is broken, you can't launch app, and even shutting down the consoles is not properly possible.

- **When Launching from RetroFlow Adrenaline Booter with NP9660 driver,** it works better as it boot the other executable ! Crazy Taxi Fare Wars seems to work correctly (I haven't test it properly), but when launching SOTN from Dracula X Chronicles, it's strange : the game is booting, you can access the menu, but when you want to start or load a game, it freeze, and it break the Vita like with INFERNO....

Maybe I made something wrong ? But I think there is something strange as from RetroFlow Adrenaline Booter, the logic is not the same as from Adrenaline, and also, there is no good solution to make the Original games from Dracula X Chronicles working correctly, so I think it's an issue.

I use a Nightly build from friday 04/14/2023 and I can provide a save for testing the original game for Castevania Dracula X Chronicles (ULES00841) if necessary.

Last note maybe useful, I used to use the Vita Launcher from cy33hc, and I had no problem with it's Adrenaline Booter, if it can help you !

Thanks in advance for your work, and I can do more test if you need to.

Best Regards,

**Comment by PukeGX** [comment]
Ok, after trying many times, I manage to get something working, but there is instability : 
In fact, the SOTN game is working OK with MARCH33 driver while booting with RetroFlow, but, for that, you need to set : 
- PS Adrenaline Button to "Menu" in other settings
- Driver to "MARCH33" in the Adrenaline Settings
- And for a strange reason, it works best with EBOOT.BIN as "Exe"

With this setup, the game Works perfectly, but, there is another problem ! 

I don't know why (I try different sequence of launching PSP and PS1 games), but sometimes, RetroFlow seems to not pass the Adrenaline Option to the Adrenaline booter, and the game start with INFERNO, so it does not work as intended. 
That is why I though that there is a strange problem with Adrenaline booter at first, but in fact, **I think there is an issue with passing the option from RetroFlow to the Adrenaline Booter.**

**Comment by jimbob4000** [comment]
Castlevania Dracula X Chronicles (ULES00841) works using the default driver and default execute setting.

Crazy Taxi works when you select the March33 driver and the default execute setting (save the setting before launching).

Crazy Taxi will crash on game start using default settings in both RetroFlow and also Vita launcher.

I don't think there's an issue with RetroFlow, if you find a game doesn't work, it's best to research which driver to use rather than trial and error as choosing the wrong one will cause problems shutting down the vita.

**Comment by PukeGX** [comment]
Hello !
Thanks for you answer.

"When you are changing the drivers etc. in RetroFlow are you saving the change before launching?"
--> Yes, I am !


"Or if you can say, I selected this driver, but it's loading a different one."
--> after some trial and error, it's the last issue I have with retroflow : I save setup to launch with MARCH33, but when launching with retroflow, I will say about 1 times of 4, it boot with the default settings instead, I saw this in the Booter menu in Adrenaline : it fall back to INFERNO (the default). 
I will try to create a bubble to make some tests is the behavior is the same.


"Castlevania Dracula X Chronicles (ULES00841) works using the default driver and default execute setting."
--> The main game yes works without problem, but you can unlock Original Game while playing ("Symphony of the Night" and "Rondo of Blood"), and when you launch these games within the main menu, it's where the default driver does not work.
It just strange it's that from Adrenaline, the game works totally with INFERNO, but this is probably a problem with Booter in fact.

And for information, I'm using Adrenaline v7 and booter 1.3

**Comment by PukeGX** [comment]
Re-Hello,

Because long text isn't always the best, I made a video to show you what's happen :

https://user-images.githubusercontent.com/53452062/233013723-42103b4f-5a25-44ca-b922-ff68678edea1.mp4

Today it's always failed to launch with MARCH33, unless I go in the Adrenaline menu and re-save the setup.


Thanks in advance !

**Comment by jimbob4000** [comment]
Hi again @PukeGX ,

Thanks for the video it was really helpful.
I think I've found and resolved the issue if you would like to try the VPK in the nightly build:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

Thanks for your patience

**Comment by PukeGX** [comment]
Thank you, man ! You're great !
It works perfectly as intented (after a load of test. :) ) ! 

Sorry for not being clear at first, I wasn't sure about what's happening, but you fix it really quickly !

Thanks you to be so fast, and to make PSVita survive the time ! This portable console is just perfect, and with RetroFlow, I love the fact to have one big menu to launch any game ! 
It's just perfect now ! 

Just Thanks !

**Comment by jimbob4000** [comment]
No problem 👍
