### ISSUE TITLE
Deleting a downloaded PS Vita cover?

### ISSUE THREAD

**Issue by 5ham5h33r** [jimbob4000/RetroFlow-Launcher#127]
I downloaded a cover for my modded FIFA, it ended up downloading the cover for a game called "Delta Strike" and replacing it with it.. now what I'm trying to do is delete the downloaded cover and revert to the cover that existed before i hit download cover. How can I do this?

**Comment by jimbob4000** [comment]
Hi 

Go to the fifa game in retroflow and press triangle button, you will see the title id for the fifa game. The cover will use this name. 

Open vitashell and delete the image from this folder:

ux0:/data/RetroFlow/COVERS/Sony - PlayStation 

Start the retroflow app, go to the settings menu, select scan settings and select rescan.
