### ISSUE TITLE
Add TG16/PCE roms

### ISSUE THREAD

**Issue by gzubsc** [jimbob4000/RetroFlow-Launcher#13]
Hi,
Could you add the TurboGrafx16/PCEngine roms please?
There are some great SHMUPs and plateformers.

Anyway, awesome work and beautifull launcher, thanks for your great work !

**Comment by jimbob4000** [comment]
Thanks, I'll look into it

**Comment by jimbob4000** [comment]
I've released a new version with resolves the issue:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.0
