### ISSUE TITLE
Adding or removing Homebrew to favorites duplicates the app

### ISSUE THREAD

**Issue by etharos** [jimbob4000/RetroFlow-Launcher#130]
RetroFlow-Launcher Version 6.0.0

Adding or removing Homebrew to favorites duplicates the app. For the rest of the games/categories, it seems to work fine. Adding homebrew to the any collection does not cause this error - it works fine. 

Rescanning the collection - fixes the problem.

![2](https://user-images.githubusercontent.com/10764145/234224898-42b1724a-fd94-475c-8d96-88abb9adc046.jpeg)
![1](https://user-images.githubusercontent.com/10764145/234224909-f823a85b-b42c-4883-b293-58ef44cf68dd.jpeg)
![3](https://user-images.githubusercontent.com/10764145/234224912-e1f8d706-e1f2-417b-9b98-085254556576.jpeg)

**Comment by jimbob4000** [comment]
Hi, thanks for reporting.

It should be fixed in the nightly version, please download that VPK and let me know how it goes.
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

Thanks again

**Comment by etharos** [comment]
Problem solved in 2023-04-26-RetroFlow :)
