### ISSUE TITLE
Make Retroflow Adrenaline Launcher take the launched app ID

### ISSUE THREAD

**Issue by Axce** [jimbob4000/RetroFlow-Launcher#132]
I'll explain myself:

When I launch a PSP/PSX game, Retroflow Adrenaline Launcher will start with the following ID: "RETROLNCR".
It would be nice if it started with the launched GameID (e.g. ULES00850), like when we start the game through Adrenaline or with a bubble.
This is relevant for apps like reVita or BetterTrackPlug, that use the current app ID for some features.

I don't know if the source code is public, so I don't know if it is possible though.
Thanks for your help!

**Comment by Axce** [comment]
I can only understand what the AutoMakeBootBin function does: I guess we could add the app ID in RetroLauncher's boot.bin with this code.
But I dont know what RetroLauncher does with it, and I'm not sure where to look at in Adrenaline's code unfortunately.

**Comment by Axce** [comment]
I just saw that Vita Launcher has the same problem with its ADRLANCHR.

**Comment by jimbob4000** [comment]
Thanks, I don't really see a fix for this.

Renaming the app folder won't work the vita won't be able to launch it.
It may be possible by editing the app.db and also the launcher folder but I don't think thats very safe.

Another approach would be to leave a temporary file with the PSP/PS1 title ID for BetterTrackPlug and reVita to read, but that would need them to add support for it. Vita Launcher and RetroFlow could write to the same file location for the temporary file.

If Vita Launcher find a way round it I'll see if it can be added too, but for the timebeing I'll close the issue.
