### ISSUE TITLE
Feature request - RetroArch PS1 CHD extension

### ISSUE THREAD

**Issue by InsanePrimate** [jimbob4000/RetroFlow-Launcher#133]
As the title states, the RetroFlow-Launcher only detects the .m3u files created for the multi disc games (launches them fine too... seems to work as intended) but NONE of the single disc games show up after a scan. Could it be that RetroFlow is looking for .bin/.cue files and since all my games are in CHD format (as advised by RetroArch/PCSX ReARMed) they are simply not detected?

**Comment by jimbob4000** [comment]
CHD isn't on the list of supported extensions for that core:

https://docs.libretro.com/library/pcsx_rearmed/

**Comment by InsanePrimate** [comment]
> 
Has to be an oversight. CHD has been supported for a while now! Runs perfectly fine for me (better than .bin/.cue in fact) It even states a feature that only works with CHD "'Precache': Loads disk image into memory for faster access (Note: CHD only)."  on the site you posted

**Comment by InsanePrimate** [comment]
https://github.com/libretro/libretro-super/blob/master/dist/info/pcsx_rearmed_libretro.info

**Comment by jimbob4000** [comment]
Thanks, I've added support for CHD to the nightly build if you would like to try that VPK:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

You will need to rescan for them to show up.

**Comment by InsanePrimate** [comment]
I am scanning right now XD

**Comment by InsanePrimate** [comment]
> Thanks, I've added support for CHD to the nightly build if you would like to try that VPK: https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly
> 
> You will need to rescan for them to show up.

I worked... only problem is now that the multi discs (which were in a subfolder called "multi disc") also show up as games next to the .m3u files for them... would it be possibly to exclude those somehow? If not, I will simply move them into a different folder and make new .m3u files pointing to that one! XD

**Comment by jimbob4000** [comment]
So you want chd in subfolders to be excluded?

**Comment by InsanePrimate** [comment]
That would require a check for .m3u files and then to exclude CHD files with the same file name (excluding the Disc 1, Disc 2, Disc 3 etc. on the multi disc CHDs)...
