### ISSUE TITLE
Incorrect Release Note

### ISSUE THREAD

**Issue by dagadtwok** [jimbob4000/RetroFlow-Launcher#134]
Hello, 
Theres a minor issue in the latest Release notes.
At the Thanks section it says I updated the Polish translation while SK00RUPA was the one who commit those changes.

**Comment by jimbob4000** [comment]
Hi @dagadtwok , 

Thanks for letting me know, I've now credited SK00RUPA for the Polish translation.

Also, I just noticed that I didn't credit you in the release notes.
I added you in the main front page readme, but the release notes were an oversight, this has been fixed, apologies.
