### ISSUE TITLE
Uninstalling all PSP bubbles with Adrenaline Bubble Manager also uninstalls the RetroFlow Adrenaline Launcher

### ISSUE THREAD

**Issue by InsanePrimate** [jimbob4000/RetroFlow-Launcher#135]
Just a heads-up: uninstalling all PSP bubbles with Adrenaline Bubble Manager (mark & uninstall all option) also uninstalls the RetroFlow Adrenaline Launcher. The https://github.com/ONElua/AdrenalineBubbleManager app sees (and lists) the RetroFlow Adrenaline Launcher as one of its custom build bubbles... not sure if there is anything that can (or should) be done about it...

**Comment by jimbob4000** [comment]
I don't there's anything I can do about that unfortunately, just don't uninstall it, or install again afterwards.
