### ISSUE TITLE
Horizon Chase Turbo Cover (PCSH10315)

### ISSUE THREAD

**Issue by xSignificant** [jimbob4000/RetroFlow-Launcher#136]
![PCSH10315](https://user-images.githubusercontent.com/5414159/235567810-e37fbd95-6f82-4eaa-b02b-b17ed2e0552c.jpg)

**Comment by jimbob4000** [comment]
Thanks,

I really don't know what the issue could be.
Your image worked for me named as "Horizon Chase.png" and also "PCSH10315.png".

I've uploaded the standard edition cover for the game, so you can download it in the app.
The cover is very similar to the square icon, so the difference is subtle.

I've attached the one I uploaded and also the limited edition version (same artwork as the one you uploaded).
Both were resized and compressed using png 8 compression.

[PCSH10315 Cover.zip](https://github.com/jimbob4000/RetroFlow-Launcher/files/11376204/PCSH10315.Cover.zip)

I'm afraid I'm going to close the issue as I can't replicate it and everything seems fine my side.

**Comment by xSignificant** [comment]
Thanks!

Let me know if you need anything more from to troubleshoot in the future.
