### ISSUE TITLE
PSV Covers are cropped off. 

### ISSUE THREAD

**Issue by InsanePrimate** [jimbob4000/RetroFlow-Launcher#137]
PSV Titles top are cropped off on the top. Quite a lot of my custom covers are being cropped off at the top since the app is adding the blue PS Vita line/logo ate the top over the 250x320 PNGs. It is not noticeable on many titles but on original covers which state "Only On Playstation" and/or "Compatible With Vita TV" it is often cropped in a very unsightly way... Would it be Possibly to mage the adding of the blue logo/line at the top optional?

**Comment by jimbob4000** [comment]
The masthead is there to make the cover uniform, at some point I'll stop creating covers, so it's important to keep it.

I don't think a setting will be added, but you can try the photoshop template when creating covers to see if it helps, or create your own to find the sweet spot of visibility. 

https://github.com/jimbob4000/hexflow-covers/tree/main/sources

Alternatively, edit the box png file in the app folder to remove the top.

**Comment by InsanePrimate** [comment]
> 

Removing the top leaves an empty space...
