### ISSUE TITLE
Cso supoort

### ISSUE THREAD

**Issue by AireagoirSteam** [jimbob4000/RetroFlow-Launcher#16]
Hello was wondering if CSO support could be added to retriflow since adrenaline seems to support it and adrenaline bubble menu supports adding a bubble for it.

Yet retroflow crashes when trying to launch any CSO game and outright crashes and errors when trying to download cover art for one.

**Comment by jimbob4000** [comment]
Hi, I've just released a new version with has support for cso files along with other improvements:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.0
