### ISSUE TITLE
Error 560: attempt to index global 'romname_region" (a nil value)

### ISSUE THREAD

**Issue by MessiahMozgus** [jimbob4000/RetroFlow-Launcher#17]
Cant launch. Vita 2000 japan import model running 3.60 with Enso_Ex.

**Comment by jimbob4000** [comment]
Hi, have the PSP ISO's been renamed like the following:

`Cars 2 (US) [UCUS-98766].iso`

Using parenthesis () for the region and square brackets [] for the title?

**Comment by MessiahMozgus** [comment]
That has nothing to do with RetroFlow not launching.

**Comment by jimbob4000** [comment]
I cannot replicate or resolve the issue without more information. 

If you can identify the problem file and post more details it would be great.

**Comment by MessiahMozgus** [comment]
No idea. I just installed the app to check it out and did nothing else. I wouldn't know where to even begin to help you on that.

**Comment by jimbob4000** [comment]
Okay, there's a guide on the GitHub page which may help. 

The app scans two existing folders:

ux0:pspemu/PSP/GAME/
ux0:pspemu/ISO/

The problem is most likely something you have within those folders.

**Comment by jimbob4000** [comment]
I think this may be related to PSP iso files being named with just the title ID. 

XXXXXXXX.iso

Renaming as per the guide may fix the issue.
