### ISSUE TITLE
VitaApps Category, renaming games, and multiple themes (ENHANCEMENT)

### ISSUE THREAD

**Issue by Thekenbaum** [jimbob4000/RetroFlow-Launcher#18]
I feel like there should be a category for the native built-in vita apps (Such as the trophy, video, music, and message app).
I often use the video and music app on my vita to either watch anime or to listen to music (I have a plugin that allows me to play music in the background of games and such).

As for the renaming games suggestion, OneMENU has the option to rename the games which is handy for the several games I have that are Japanese with English patches (PuyoPuyo Teris, Steins;Gate Elite, Taiko no Tatsujin V edition, etc.) or certain games with minor grammatical errors in their title ID (Cough cough, the missing space in Danganronpa 2, cough cough) which could cause games to appear outside of alphabetical order. I also noticed that after renaming the games via OneMenu, they still appear to have their original names listed as though I didn't change them.

Also had an idea for the use of multiple "themes", or to put it more simply, a folder for different background images and a folder for different background music that you can switch between in the options menu. (Perhaps even an option to set a custom background dependant on which menu you are in, so you can have a different background for SNES or NES Games.)

Also, one more thing of note I wanted to mention, I wanted to have an MP3 playing in the background, but every time I try I get an error message saying that it's an unsupported format. As far as I know .MP3 is the format it needs to be in, but it doesn't seem to work for me, perhaps it needs to be a specific bitrate or something, I don't know.

**Comment by Thekenbaum** [comment]
*Addendum*
Also, the option to change the text colors would be nice, I have a custom background and the white text labeling which system I'm looking at just so happens to be over a white part of my background, causing it to blend in.

**Comment by jimbob4000** [comment]
Closing issue prior to archiving
