### ISSUE TITLE
PSP and PSX have to exit Retroflow Launcher and reenter to work

### ISSUE THREAD

**Issue by Thenuke1** [jimbob4000/RetroFlow-Launcher#21]
Another issue

press x on either psp or psx games, launcher freezes cant move left or right or press any other button.... press the PS button and then enter launcher again and then it starts working ... anyone know a fix ?

happens on any PSP or PSX game...

reboot doesnt work

**Comment by Thenuke1** [comment]
strange ... i deleted Adrenaline bubble manager, and adrenaline bubble booter

and the app worked fine if i only keep adrenaline launcher but once i restart the vita the problem starts again

**Comment by Thenuke1** [comment]
UPDATE . i started messing with it ...
if i replace the Index.lua file with the latest HexFlow Index.lua file it seems to fix the psp issues and they launch perfect,
the psx games launch now instead of freeze the app but once they open it i get this error c0-8976-0

**Comment by jimbob4000** [comment]
Thanks for reporting, I'll look into it. 

P.S. The index files for Hexflow and Retroflow aren't interchangeable.

**Comment by Thenuke1** [comment]
> Thanks for reporting, I'll look into it.
> 
> P.S. The index files for Hexflow and Retroflow aren't interchangeable; Hexflow uses bubbles for PSP and PSX.

gotcha thanks for responding .... ive tried it on 3 vitas and everyone had the same issue ... im working on a 4th vita going to redownload and hope for the best

**Comment by jimbob4000** [comment]
Hi, I've hopefully fixed the issue if you would like to test a pre-release version here:
[https://we.tl/t-3v5csIyblf](https://we.tl/t-3v5csIyblf)

Let me know how it goes, thanks

**Comment by jimbob4000** [comment]
> > Thanks for reporting, I'll look into it.
> > P.S. The index files for Hexflow and Retroflow aren't interchangeable; Hexflow uses bubbles for PSP and PSX.
> 
> gotcha thanks for responding .... ive tried it on 3 vitas and everyone had the same issue ... im working on a 4th vita going to redownload and hope for the best

Hi, I've hopefully fixed the issue if you would like to test a pre-release version here:
[https://we.tl/t-3v5csIyblf](https://we.tl/t-3v5csIyblf)

Let me know how it goes, thanks

**Comment by Tsume-Ridea** [comment]
The pre-release version is working for me =)

**Comment by jimbob4000** [comment]
> The pre-release version is working for me =)

Great stuff, I've got a bit more work to do on it, should be out in the next week hopefully. 

Give me a shout if you hit any problems, hoping this one will be more stable.

**Comment by GentMAB** [comment]
Is this related to when clicking the RetroFlow Adrenaline Launcher and it says "Could not start adrenaline_kernel.skprx. Please reboot or use the AdrBubbleBooterInstaller."?

**Comment by jimbob4000** [comment]
> Is this related to when clicking the RetroFlow Adrenaline Launcher and it says "Could not start adrenaline_kernel.skprx. Please reboot or use the AdrBubbleBooterInstaller."?

Hi, this thread is for a different issue. 

Please see closed issues
[https://github.com/jimbob4000/RetroFlow-Launcher/issues/22](22) or [https://github.com/jimbob4000/RetroFlow-Launcher/issues/9](9) for help.

**Comment by GentMAB** [comment]
> > Is this related to when clicking the RetroFlow Adrenaline Launcher and it says "Could not start adrenaline_kernel.skprx. Please reboot or use the AdrBubbleBooterInstaller."?
> 
> Hi, this thread is for a different issue.
> 
> Please see closed issues 22 or 9 for help.

Thank you appreciate that! My filter wasn't showing closed issues

**Comment by Thenuke1** [comment]
will try thank you !!!

**Comment by jimbob4000** [comment]
I've got further since sharing the file. 

Maybe hold off until the next release, should be later today. Will message here when released.

**Comment by jimbob4000** [comment]
This should be resolved with the latest [3.1 release](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.1).
