### ISSUE TITLE
PSP and PSX error: Could not load adrenaline_kernel.skprx

### ISSUE THREAD

**Issue by Tsume-Ridea** [jimbob4000/RetroFlow-Launcher#22]
If I want to start any PSP or PSX game it only shows this error message on a black screen: 
(Its not possible to take a screenshot of it)

**"Could not load adrenaline_kernel.skprx. Please reboot or use the AdrBubbleBooterInstaller."** 

Same error message if I do start only the "RetroFlow Adrenaline Launcher"-Bubble. 

I´m using Adrenaline v7 and its woking without any problems with PSP and PSX games. They have all the right names and no subcategory folders are used like in your instructions. Covers are loading like they should. The only plugins which I´m using for PSP are the remastered controls by theFlow.
The "adrenaline_kernel.skprx" path is written to the tai config.txt (ur0). Adrenaline itself is installed in ux0 (with SD2Vita) like it should be. I made a clean installation of it, no update with old files. 
My FW is 3.65 Enso and I´m not using repatch or overclocking.

**Comment by jimbob4000** [comment]
Please see this closed issue for help:
https://github.com/jimbob4000/RetroFlow-Launcher/issues/9

**Comment by Tsume-Ridea** [comment]
Thank you, this is working. But now I have the same bug like in https://github.com/jimbob4000/RetroFlow-Launcher/issues/21 
I will try your pre-release version.
