### ISSUE TITLE
If Vita homebrew is in homebrew category, it's png cover cannot be found

### ISSUE THREAD

**Issue by Invictaz** [jimbob4000/RetroFlow-Launcher#25]
Example, Daedalus64 (Vita Homebrew)

If placed in Homebrew category then the DEDALOX64.png cannot be found.
When category override is used to move it to VITA games, the png is found correctly.

Intended behavior is that it should always look for $appname.png even when it's in the "wrong" category

**Comment by jimbob4000** [comment]
Are you after a separate cover folder called homebrew?

**Comment by Invictaz** [comment]
Yes, something like that

**Comment by jimbob4000** [comment]
This should be resolved with the latest [3.2 release](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.2).

A homebrew cover folder has been added for artwork overrides.
