### ISSUE TITLE
Could not load adrenaline_kernel.skprx

### ISSUE THREAD

**Issue by diablos872001** [jimbob4000/RetroFlow-Launcher#28]
Hello.
I've got a problem to launch PSP and PSX games from RetroFlow Launcher.
I've renamed them correctly, and I see them in RetroFlow Launcher also with correct cover (downloaded).
But when I choose a PSX or PSP game, and RetroFlow opens -> RetroFlow Adrenaline launcher nothing happen but only a message:
"Could not load adrenaline_kernel.skprx. Please reboot or use the AdrBubbleBoosterInstaller"

Where am I wrong?
I do not want to create a bubble for each games, to avoid the utility of RetroFlow Launcher.

**Comment by jimbob4000** [comment]
More info here:

https://github.com/jimbob4000/RetroFlow-Launcher#issues-loading-games-with-adrenaline

Also see closed issues.
