### ISSUE TITLE
[Feature Reuest] Search, Add to favourites, Skip alphabetically

### ISSUE THREAD

**Issue by mikesierra85** [jimbob4000/RetroFlow-Launcher#29]
Hi, I mentioned this in the Reddit post, so here is a brief explanation:

- A button would bring up the keyboard to type and search for a title, maybe show results based on the first 3 characters. This is useful for people with a large library of games.
- An option to add titles to "Favourites" and have a new "Favourites" section
- The option to jump to the next letter in the games list, instead of scrolling across the whole games list to reach a game that starts with the letter "W" for example, maybe a double tap on the R1/L1 would jump between the previous and next letter on the list.

Thank you.

**Comment by arongkatz** [comment]
Thanks i couldnt explaned it better. About the favorites feature, perhaps this could be an option in the DETAILS section where you can choose to add it to favourites

**Comment by jimbob4000** [comment]
Hi, add to favorites has been added to the [3.4 release](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.4), I'll update the feature request title.

**Comment by arongkatz** [comment]
Awesome!!!

**Comment by jimbob4000** [comment]
Search now available in [version 3.5 ](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.5)
Alphabetical may not happen, I've created a seperate issue, so I can close this one.
