### ISSUE TITLE
Some PSP games not loading correctly - After initial loading screens, redirects to "Virtual" PSP

### ISSUE THREAD

**Issue by billabongbruno** [jimbob4000/RetroFlow-Launcher#30]
Hey there.

First of all, I would just like to thank you for your work.
It is, in my opinion, the best Launcher out there and you packed it with so many cool and useful features that I could not go without saying it and thanking you.

So, thank you for you hard work. It is really appreciated.

On to the issue now, though:

So, even though almost everything works flawless for me, I stumbled upon a little issue that I tried to resolve, but to no avail.

As the title of the issue suggests, there are some PSP games, namely "ULUS-10192" (Sega Genesis Collection) and "ULUS-10070" (Splinter Cell Essentials) that do in fact load perfectly at first, using RetroFlow Launcher, but after choosing a game from the main menu (in ULUS-10192) and after the initial loading screen (in ULUS-10070), I get redirected to the "Virtual" PSP used by Adrenaline. I don't even see the Adrenaline menu, it just boots right into the "Virtual" emulated PSP.

From there I can boot the game with no issues, but I do need to load it up from scratch.
As I understand, this is not the expected outcome, or am I missing something here?

Relevant information for this issue:
1 - Other games, such as "ULES-00826" (Tomb Raider Anniversary) and "ULES-00283" (Tomb Raider Legend) do not suffer from this issue, they boot all the way into the game and are 100% playable;

2 - I am using my PSVita in my native language, as well as RetroFlow itself, which is Portuguese (Portugal).

Truly sorry to be bothering you, but is there any way you can shed some light on the subject?

Thank you in advance.

Best regards,
Bruno.

**Comment by jimbob4000** [comment]
Hi, does the problem exist when opening the problem games from within Adrenaline, vita launcher, or from a bubble created by adrenaline bubble manager?

Thanks

**Comment by billabongbruno** [comment]
> Hi, does the problem exist when opening the problem games from within Adrenaline, vita launcher, or from a bubble created by adrenaline bubble manager?
> 
> Thanks

Hello there.

Thank you for your quick reply.

Regarding the issue at hand:

1 - It does NOT happen if I use a Bubble created using ABM nor does it occur while launching it through Adrenaline.
2 - I have changed both my System languages and RetroFlow to English and the issue persists.

Hope this feedback helps in any way.

I once again thank you for your hard work.


Best regards,
Bruno Santana.

**Comment by jimbob4000** [comment]
Hi , what settings are you using for the adrenaline bubbles that work?

I can't seem to get them to launch properly using adrenaline bubble manager either.
I think the driver may need to be changed to MARCH33?

Thanks

**Comment by jimbob4000** [comment]
Closing issue prior to archiving

**Comment by jimbob4000** [comment]
Driver support has been added
