### ISSUE TITLE
Error 3928: attempt to index a nil value

### ISSUE THREAD

**Issue by GentMAB** [jimbob4000/RetroFlow-Launcher#32]
Crashing every time I go to Game Gear Games with the error code

"An error occurred: [string "?"]3928: attempt to index a nil value"

**Comment by GentMAB** [comment]
Along with that it is not reading the names of the files correctly either, see attached image as it will download the correct thumbnail but has the wrong title which I'm guessing is causing part of the crash.  That first game that is highlighted is actually The Adventures of Batman & Robin.  See attached images.  
![PXL_20211207_045723489](https://user-images.githubusercontent.com/12135383/144969326-3f77d6b8-0c83-43f6-96d0-b0c407d80d52.jpg)
![PXL_20211207_045922793](https://user-images.githubusercontent.com/12135383/144969330-6914efc3-a158-4947-85f1-325f1f282df8.jpg)
![PXL_20211207_045936169](https://user-images.githubusercontent.com/12135383/144969332-bb5dfa57-9f8d-4f85-ae23-f0687d119b17.jpg)

**Comment by jimbob4000** [comment]
Hi which version number of retroflow are you using? Thanks

**Comment by GentMAB** [comment]
I was using 3.1 just updated to 3.2 and can confirm it is still happens in that one as well.

**Comment by jimbob4000** [comment]
Thanks for reporting.
This should be resolved with the latest [3.3 release](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.3).
