### ISSUE TITLE
uma0 support for psp and psx

### ISSUE THREAD

**Issue by jimbob4000** [jimbob4000/RetroFlow-Launcher#33]

**Comment by Makein** [comment]
Yes, need this support too

**Comment by Makein** [comment]
I can launch psp games from RetroFlow.Adrenaline.Launcher.v2.0.vpk , but it's same as adrenaline app and changed settings to uma0 doesn't save after reboot

**Comment by Makein** [comment]
Okey, I fix it
Open `ux0:/app/RETROFLOW/index.lua`
Find any `ux0:/pspemu` and change to `uma0:/pspemu`

**Comment by Juanobanano2000** [comment]
hey team, 
how i can load psp games in ux0 and uma0 at the same time
i have games i both directories
thanks

**Comment by jimbob4000** [comment]
It's currently setup to only scan the ux0 PSP folder. Additional code would need to be added to scan uma0. 

The extract you mentioned is only a small portion. 

I may add it in future, but for the time being, may be worth moving them to ux0.

**Comment by Makein** [comment]
> hey team, how i can load psp games in ux0 and uma0 at the same time i have games i both directories something like this ? -- ROM Folders local romFolder = "uma0:/rom/" local romFolder_N64 = romFolder .. "Nintendo - Nintendo 64" local romFolder_SNES = romFolder .. "Nintendo - Super Nintendo Entertainment System" local romFolder_NES = romFolder .. "Nintendo - Nintendo Entertainment System" local romFolder_GBA = romFolder .. "Nintendo - Game Boy Advance" local romFolder_GBC = romFolder .. "Nintendo - Game Boy Color" local romFolder_GB = romFolder .. "Nintendo - Game Boy" local romFolder_MD = romFolder .. "Sega - Mega Drive - Genesis" local romFolder_SMS = romFolder .. "Sega - Master System - Mark III" local romFolder_GG = romFolder .. "Sega - Game Gear" local romFolder_PSP_GAME = "ux0:/pspemu/PSP/GAME" local romFolder_PSP_ISO = "ux0:/pspemu/PSP/ISO" local romFolder_PSP_ISO = "uma0:/pspemu/PSP/ISO" local romFolder_MAME_2000 = romFolder .. "MAME 2000" local romFolder_AMIGA = romFolder .. "Commodore - Amiga" local romFolder_TG16 = romFolder .. "NEC - TurboGrafx 16" local romFolder_PCE = romFolder .. "NEC - PC Engine" thanks

Hello, here I add support for both (ux0 and uma0) locations. It's should scan roms and run them fine 
(But not sure about psp emulation, bcs in adrenaline I not remember option for combined ux0&uma loading. Need testing.)
[Upgraded.zip](https://github.com/jimbob4000/RetroFlow-Launcher/files/7760385/Upgraded.zip)

**Comment by Makein** [comment]
> > hey team, how i can load psp games in ux0 and uma0 at the same time i have games i both directories something like this ? -- ROM Folders local romFolder = "uma0:/rom/" local romFolder_N64 = romFolder .. "Nintendo - Nintendo 64" local romFolder_SNES = romFolder .. "Nintendo - Super Nintendo Entertainment System" local romFolder_NES = romFolder .. "Nintendo - Nintendo Entertainment System" local romFolder_GBA = romFolder .. "Nintendo - Game Boy Advance" local romFolder_GBC = romFolder .. "Nintendo - Game Boy Color" local romFolder_GB = romFolder .. "Nintendo - Game Boy" local romFolder_MD = romFolder .. "Sega - Mega Drive - Genesis" local romFolder_SMS = romFolder .. "Sega - Master System - Mark III" local romFolder_GG = romFolder .. "Sega - Game Gear" local romFolder_PSP_GAME = "ux0:/pspemu/PSP/GAME" local romFolder_PSP_ISO = "ux0:/pspemu/PSP/ISO" local romFolder_PSP_ISO = "uma0:/pspemu/PSP/ISO" local romFolder_MAME_2000 = romFolder .. "MAME 2000" local romFolder_AMIGA = romFolder .. "Commodore - Amiga" local romFolder_TG16 = romFolder .. "NEC - TurboGrafx 16" local romFolder_PCE = romFolder .. "NEC - PC Engine" thanks
> 
> Hello, here I add support for both (ux0 and uma0) locations. It's should scan roms and run them fine (But not sure about psp emulation, bcs in adrenaline I not remember option for combined ux0&uma loading. Need testing.)

I fix errors and test it.
So, now roms would be scanned on ux0&uma0.
All works, cheers!

jimbob4000, you can add it in your repo and vpk releases

File should be placed on  `ux0:\app\RETROFLOW\
[index.zip](https://github.com/jimbob4000/RetroFlow-Launcher/files/7760682/index.zip)
`

**Comment by jimbob4000** [comment]
Feature now available in [version 3.5 ](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.5).
Please configure Adrenaline to use either uma0 or ux0.
I tried to get both working similtaneously, but couldn't manage it. Maybe in future.
