### ISSUE TITLE
CRC / MD5 scraping for retro covers

### ISSUE THREAD

**Issue by dotexe1337** [jimbob4000/RetroFlow-Launcher#35]
It would be nice if we could use ScreenScraper.fr as a cover art source. It seems to match retro games a lot better than the current cover art source does, in my experience. My romset ends up with a large number of the games missing covers on RetroFlow's current source, but with ScreenScraper.fr on Playnite and Batocera almost all of my games match perfectly.

**Comment by jimbob4000** [comment]
Thanks for the suggestion. 

Their site is quite unstable going down for maintenance a lot, plus requires keys and passwords.

Cover accuracy could be improved by scanning the rom itself but it's quite a big job and may slow the scanning further. 

Maybe copy over the scraped covers to the vita to fill in the gaps, or try renaming the Roms to match the no-intro naming.

**Comment by dotexe1337** [comment]
Hi, as for the keys/passwords, you can create a free account rather than having to pay. I have a free account and can scrape a maximum of 10,000 requests per day, works very well for me.
Copying the files manually is a good idea, I think I can use a program on my PC, pointing it at the Vita's rom folder exposed over USB and then put the output path as wherever RetroFlow stores its covers.

**Comment by jimbob4000** [comment]
Closing issue prior to archiving
