### ISSUE TITLE
The App don't find the adrenaline bubbles of Psp and psx 

### ISSUE THREAD

**Issue by Juanobanano2000** [jimbob4000/RetroFlow-Launcher#36]
Hi team. This app is amazing and load very fast. Thanks so much. The app don't find the adrenaline bubbles created in my vita. This is the best way to get psx and Psp because there are game files in any directories like ux0 uma at the same time. Thanks very much

**Comment by jimbob4000** [comment]
Hi, this is intentional, as otherwise the game would appear twice. 

There's a legacy version available which uses bubbles for adrenaline.

**Comment by Juanobanano2000** [comment]
Hi team 
It's ok but how it can load psp cso in diferentes director ies like at the same time. Thanks very much

**Comment by jimbob4000** [comment]
CSO files are supported, they should be in the same directory as iso files.
