### ISSUE TITLE
Correct ROM naming system?

### ISSUE THREAD

**Issue by Makein** [jimbob4000/RetroFlow-Launcher#37]
Can you give example how roms should be named?
Covers dl work only for GBA ROMs for me (psp, vita, psx works too)
I need naming for NES, SNES, MD

**Comment by jimbob4000** [comment]
Names will need to follow the no intro names. 

NES is here for example:
[https://datomatic.no-intro.org/index.php?page=search&s=45](https://datomatic.no-intro.org/index.php?page=search&s=45)

Games can be renamed on mass using romcenter and no intro data from the link above.

**Comment by jimbob4000** [comment]
Closing issue prior to archiving
