### ISSUE TITLE
PSM Compatibility

### ISSUE THREAD

**Issue by Juanobanano2000** [jimbob4000/RetroFlow-Launcher#38]
hi team, there are any option to load PSM Games?, Thanks very much

**Comment by jimbob4000** [comment]
Thanks for the info. 
It's not something I have looked into. It's not supported at the moment, maybe in future.

**Comment by jimbob4000** [comment]
Closing issue prior to archiving

**Comment by jimbob4000** [comment]
Added to the nightly build:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

**Comment by Juanobanano2000** [comment]
AWESOME, i will try it, thanks very much
