### ISSUE TITLE
[Enhancement] Disable "close app" prompt when launching games

### ISSUE THREAD

**Issue by JohnGhostly** [jimbob4000/RetroFlow-Launcher#40]
Since the app is a launcher it would be useful to be able to disable the prompt to close retroflow when launching applications

**Comment by jimbob4000** [comment]
Thanks, the message shouldn't appear too much. 

I'll have a look, although when I looked last the documentation to achieve this is missing. Hopefully down the line it may be less frequent.

**Comment by Duly-noted1** [comment]
What would be more useful would be a plugin that instructs the vita to immediately launch retroflow every time another app is closed out of. That way we can use autoboot to get into retroflow, and after closing a game we will go right back to retroflow

**Comment by jimbob4000** [comment]
Closing issue prior to archiving
