### ISSUE TITLE
[Feature Request] Recently played optional category

### ISSUE THREAD

**Issue by PalSwap** [jimbob4000/RetroFlow-Launcher#41]
#29 covers a lot of the usability enhancements I'd love to see in this great launcher, but building off on it, another feature I would find useful in my day to day usage would be a Recently Played category to go back to the last n (I don't know? 10 or 20?) games launched regardless of their platform. This category could be optionally toggled like the Homebrew category is.

I genuinely don't know how feasible this is, particularly in rendering in a single category box arts with different formats, but I figured it wouldn't hurt to ask.

**Comment by peterdickx** [comment]
This should be farely easy to implement, i'll take a look at it

**Comment by jimbob4000** [comment]
This should be in the next release.

**Comment by jimbob4000** [comment]
Hi [version 3.4](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.4) is out with the optional recently played category. I'll close the issue, please open a new one if you encounter bugs.
