### ISSUE TITLE
Support for TG16/PCE cue files

### ISSUE THREAD

**Issue by PalSwap** [jimbob4000/RetroFlow-Launcher#42]
Thank you for adding TG16/PCE support. One last thing we would need is support for cue files to play CD games. As far as I know, as long as the cue file is correctly formatted and points to the right bin file, it will load the game. I haven't tried messing with the code to see if adding cue file support was enough though.

**Comment by jimbob4000** [comment]
Hi, thanks for the suggestion. This is now available in the [3.4 release](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.4).
