### ISSUE TITLE
Creating own categories

### ISSUE THREAD

**Issue by desolutionX** [jimbob4000/RetroFlow-Launcher#47]
Suggestion for improvement
The fork is well done. In addition to the wish for a favorites category in another Issuepost. Would it be possible to have the ability to create own Categories? In my way iam thinking about creating different Genre like e.g RPG, Hack` Slay, Fighting, Racing .... where i can sort my Games and scroll threw it.  The abilitiy to change the category is yet given. And maybe adding the possibility to scroll threw the Categories by pushing up or down, not only pressing square button.

**Comment by jimbob4000** [comment]
Closing issue prior to archiving

**Comment by jimbob4000** [comment]
Closing issue prior to archiving

**Comment by jimbob4000** [comment]
Hi again,

I've added custom categories (Collections) to the nightly pre-release, free to try it out: https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

How to create a collection:

•	⁠Press the triangle button on a game and press the triangle button again to bring up the mini menu, then select 'Add to collection' to bring up the options.

Renaming or deleting a collection:

•	⁠Collections can be renamed/deleted by going to the main settings menu 'Other settings > Edit collections'.

**Comment by desolutionX** [comment]
Hi Jimbob,

i`ve experimented with the nightly, created collections and sorted the games. It worked flawless, including to show collections only by D-Pad up.

Thank you for taking time to create this feature
