### ISSUE TITLE
Added:Zx-Spectrum

### ISSUE THREAD

**Issue by lineacero** [jimbob4000/RetroFlow-Launcher#48]
Added:spectrum please,,wonderfull Zx-spectrum.
Thanks retroflow wonderfull yeahhh

**Comment by jimbob4000** [comment]
I'm stuggling with the Zx Spectrum.

There's a vast library of games and their filenames vary depending on where they come from.

I started matching covers around 7,000 so far, but the more I look around, there's hardly any matching the game names out there.

**Comment by jimbob4000** [comment]
I can add it down the line, but for the most part covers will need to be added manually by users. 

P.S. The Zx spectrum was my first experience of gaming. Jetpac was awesome.

**Comment by lineacero** [comment]
The Zx spectrum was my first experience of gaming,,yes,,yes,wonderfull ZX-Spectrum,,,yeahhhhhhh

covers will need to be added manually by users yessss,,yeahhh,,wonderfull brother

**Comment by lineacero** [comment]
thank my friend

**Comment by Vecinagamer** [comment]
yeahhhh Zx-Soectrum yeahhhhhhh

**Comment by jimbob4000** [comment]
Feature now available in [version 3.5 ](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.5)
