### ISSUE TITLE
[Feature request] - Play more than one song in the menus

### ISSUE THREAD

**Issue by nad45** [jimbob4000/RetroFlow-Launcher#51]
Would it be possible?
It's boring to have the same song playing over and over in the menu.
Of course, I could change the mp3 but it would be more convenient to put several mp3 (Music, Music1, Music2...) so the app can ramdom play the tracks.

**Comment by jimbob4000** [comment]
Hi, I think it's possible.

Note to self:
Create music directory, add to table, play [1].

**Comment by Vecinagamer** [comment]
yeahhhhhh

**Comment by jimbob4000** [comment]
Closing issue prior to archiving

**Comment by jimbob4000** [comment]
Feature added
