### ISSUE TITLE
Vita system apps category

### ISSUE THREAD

**Issue by jimbob4000** [jimbob4000/RetroFlow-Launcher#53]

**Comment by jimbob4000** [comment]
Option to hide

**Comment by peterdickx** [comment]
Would it be possible to access the settings (like bluetooth devices) from withing retroflow?

**Comment by jimbob4000** [comment]
Bluetooth and wifi can be turned on by holding the down the Playstation button if that helps?

**Comment by jimbob4000** [comment]
Issues: The following apps have no known launch uri commands:
NPXS10013 PS4 Link, NPXS10094 Parental Controls, NPXS10026 Content Manager, NPXS10012 PS3 Remote Play.

Source: https://playstationdev.wiki/psvitadevwiki/index.php/Title_ID

**Comment by jimbob4000** [comment]
Closing issue prior to archiving
