### ISSUE TITLE
RetroFlow Adrenaline Launcher error

### ISSUE THREAD

**Issue by rynho** [jimbob4000/RetroFlow-Launcher#54]
I have Adrenaline installed, working well, but when try with RetroFLow Adrenaline Launcher, it reports not able to load adrenaline_kernal.skprx.

I'm using PSTV, my Adrenaline is installed under ux0 apps, but my boot config is in ur0:/tai/ folder, not sure if it is anything to do with the problem.

**Comment by jimbob4000** [comment]
More info here:

https://github.com/jimbob4000/RetroFlow-Launcher#issues-loading-games-with-adrenaline

Also see closed issues.
