### ISSUE TITLE
Feature request - Add support for ScummVM

### ISSUE THREAD

**Issue by rafaelferreira01** [jimbob4000/RetroFlow-Launcher#55]
Add support for ScummVM games.

**Comment by jimbob4000** [comment]
I don't think I can add this until Retroarch adds support.

Lauching the standalone version of ScummVM is too messy given the complexity of knowing which of the many game related files should be used in the launch command.

Closing the request for the time being, sorry.

**Comment by jimbob4000** [comment]
Scummvm has been added to the nightly build

https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly
