### ISSUE TITLE
[Feature Request] A "previous category" button

### ISSUE THREAD

**Issue by barnacleman** [jimbob4000/RetroFlow-Launcher#58]
Problem: It can feel cumbersome to have to navigate through every category sequentially. If I want to go to my final category in the list from the first category, I feel that I should be able to do that in one action with a "Previous category" button. 

Suggestion: Bind "Previous category" and "Next category" to up and down on the d-pad, respectively. This would also free up the square button in the future for another function.

**Comment by jimbob4000** [comment]
Closing issue prior to archiving

**Comment by jimbob4000** [comment]
Featured has been added
