### ISSUE TITLE
[Feature request] Setting option to change ISO driver on PSP games

### ISSUE THREAD

**Issue by Crackemtruth24** [jimbob4000/RetroFlow-Launcher#59]
Some PSP games (mostly collection or recompilation games like Metal Slug Anthology) don't work properly with the Inferno driver. Since the Retroflow Adrenaline Launcher settings go back to default when launching a game again, i wonder if its possible to add a option to always launch PSP games with a specific driver, or a way to save the booter settings on a game without lost them when I launch another game

**Comment by jimbob4000** [comment]
Closing issue prior to archiving

**Comment by jimbob4000** [comment]
Feature has been added
