### ISSUE TITLE
[Feature Request] Option to show the full filename of roms.

### ISSUE THREAD

**Issue by rafaelferreira01** [jimbob4000/RetroFlow-Launcher#60]
Good for when we have a bunch of romhacks.

For instance, i have these roms:
Legend of Zelda, The - A Link to the Past (USA).sfc
Legend of Zelda, The - A Link to the Past (Redux New GFX 9.2).sfc
Legend of Zelda, The - A Link to the Past (Redux New GFX 9.2+Disable Dash Turning).sfc

All this them are showing as Legend of Zelda, The - A Link to the Past.

**Comment by jimbob4000** [comment]
This info can be seen when you press triangle, under the version info.
