### ISSUE TITLE
[string "?"]:5116: attempt to get length of a nil value

### ISSUE THREAD

**Issue by mmayfield** [jimbob4000/RetroFlow-Launcher#66]
At the end of categories (while scrolling) instead of going back to vita category I get the error:
[string "?"]:5116: attempt to get length of a nil value

**Comment by jimbob4000** [comment]
I'm having trouble replicating the issue.
When i reach the last game it's looping back to the first without an error.

Hopefully these questions will help me replicate the issue:

- Are you using the D-Pad, Analogue sticks, Trigger buttons, or touch to scroll through the games when this happens?
- Does it happen for every game category?
- Also, is the startup scan on or off? 

Thanks

**Comment by mmayfield** [comment]
I generally run with start up scan off unless I add things. It's not at the end of a category it is at then end of the categories. So my first category is vita and my last is favorites. When I press square to go from favorites back to vita, that's when I get the error.

**Comment by mmayfield** [comment]
function GetNameAndAppTypeSelected() -- Credit to BlackSheepBoy69 - This gives a massive performance boost VS reading whole app info.
	if CatLookup then
    	if #xCatLookup(showCat) > 0 then --if the currently-shown category isn't empty
        	app_title = xCatLookup(showCat)[p].apptitle
       		apptype = xCatLookup(showCat)[p].app_type -- needed for launching games from mixed categories
        	filename = xCatLookup(showCat)[p].filename -- needed for adding to recent
    	else
        	app_title = "-"
    	end

    	if showCat == 40 and #search_results_table == 0 then
    	    app_title = lang_lines.Search_No_Results
    	end
	end
end

If I do this it works but I think it may be breaking the function.

**Comment by mmayfield** [comment]
This appears to be working properly

function GetNameAndAppTypeSelected() -- Credit to BlackSheepBoy69 - This gives a massive performance boost VS reading whole app info.
if showCat then
if #xCatLookup(showCat) > 0 then --if the currently-shown category isn't empty
app_title = xCatLookup(showCat)[p].apptitle
apptype = xCatLookup(showCat)[p].app_type -- needed for launching games from mixed categories
filename = xCatLookup(showCat)[p].filename -- needed for adding to recent
else
app_title = "-"
end
if showCat == 40 and #search_results_table == 0 then
app_title = lang_lines.Search_No_Results
end
end
end

**Comment by jimbob4000** [comment]
Okay, thanks for the info.

If you can undo any changes you have made, then change the following on line 10053:

Change `GetNameAndAppTypeSelected()` to `GetInfoSelected()`

Let me know if that solves the issue, thanks.

**Comment by mmayfield** [comment]
That appears to fix everything!

**Comment by jimbob4000** [comment]
Good stuff, thanks for reporting. I'll release a fix soon.

**Comment by jimbob4000** [comment]
Should be resolved with v3.6.1
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.6.1
