### ISSUE TITLE
Can’t open purchased PSP games. Requires Adrenaline, when not needed for purchased games. 

### ISSUE THREAD

**Issue by SoulEaterGames** [jimbob4000/RetroFlow-Launcher#67]
As the title states, I can’t open PSP games that I have purchased and downloaded from the PS store or that I transferred through content manager. It requires me to install adrenaline, but I don’t need adrenaline since the ISO’s are signed. Is there any way to open the PSP games without needed adrenaline?

**Comment by jimbob4000** [comment]
Sorry, I'm afraid this app needs adrenaline to launch psp games. 

You could try Vita launcher as an alternative to RetroFlow.
