### ISSUE TITLE
Sega 32X has wrong core assigned in index.lua

### ISSUE THREAD

**Issue by Levine91** [jimbob4000/RetroFlow-Launcher#68]
I was having issues getting 32X games to boot and it lead me to notice that you have Genesis GX Plus as the assigned core, whereas it actually should be PicoDrive, given that Genesis GX Plus does not support the 32X.

**Comment by jimbob4000** [comment]
Hi, thanks for reporting.

I've released a fix in [v3.6.2](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.6.2) if you would like to download it.
