### ISSUE TITLE
An error occurred: [string "?"]:5116: attempt to get length of a nil value

### ISSUE THREAD

**Issue by mikesierra85** [jimbob4000/RetroFlow-Launcher#69]
Running v3.6.1, this happens whenever I press DPAD Up on the main menu (PS Vita Games view).

Tried a fresh install, downloaded all covers again. the same error comes up.

**Comment by jimbob4000** [comment]
Thanks for reporting, I'll look into it and release a fix soon. 

In the meantime if you add a game to the favourites it may fix the issue until a fix is added.

**Comment by jimbob4000** [comment]
I've updated the latest release to fix the issue if you would like to download it.
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.6.2

Thanks for reporting.
