### ISSUE TITLE
Quick menu also controls launcher 

### ISSUE THREAD

**Issue by Highthorn90** [jimbob4000/RetroFlow-Launcher#71]
When retroflow is open and I go to the quick menu (holding PS button) to change some settings, the inputs control both the quickmenu and retroflow.

**Comment by jimbob4000** [comment]
Hi, thanks for reporting.

I've looked into the issue, but there's bad news I'm afriad.

I don't think there is a means for me to block the button presses in RetroFlow whilst you are in the quick menu.
Touch controls don't seem to affect the app.

If something new comes to light I'll try and fix it, but for the moment I don't think there's anything I can do, apologies.
