### ISSUE TITLE
Wrong FlyCast compatibility list website on 4.0 readme

### ISSUE THREAD

**Issue by thipeto** [jimbob4000/RetroFlow-Launcher#72]
> Flycast is required to play Dreamcast games. Also see the compatibility list (https://flycast.rinnegatamante.it/) as not all games are playable yet.

Rinnegatamante have 2 different compatibility list websites. The website for the new FlyCast is:

https://**new**flycast.rinnegatamante.it/

**Comment by jimbob4000** [comment]
Hi, thanks for the info, I've updated the readme and release notes.
