### ISSUE TITLE
I know, that new features requesting is forbidden, but...

### ISSUE THREAD

**Issue by xRiseless** [jimbob4000/RetroFlow-Launcher#73]
Sorry for bothering. Is it possible to add support for mGBA emulator into ur launcher? mGBA works way better than VBA-Next or gpsp that presented in RetroArch. I want to use ur launcher bcoz its very cool, but i also want to launch mGBA games via ur launcher. Hope u will do something with this. :з Thank you. :в

**Comment by jimbob4000** [comment]
Hi, I don't think mgba supports external launchers or bubbles. 

There is an open request with their dev team for this. 

At the moment I'm afraid it can't be added.
