### ISSUE TITLE
Issue: If path points to a folder that does not exist an error on launch

### ISSUE THREAD

**Issue by JohnGhostly** [jimbob4000/RetroFlow-Launcher#74]
I changed one of the directories to a folder but after removing the folder the program would not launch until recreating it.

**Comment by jimbob4000** [comment]
Thanks for reporting.

I've fixed the issue in the pre-release below.
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v4.0.1

I've added a check to make sure the folder exists before scanning.
