### ISSUE TITLE
(Bug\Feature) Edit game directories... ~ No option to select different drive\mountpoint

### ISSUE THREAD

**Issue by GrindLogic** [jimbob4000/RetroFlow-Launcher#76]
The bug\feature is that I got one of those 3G models...and well of course I put in not only a SD2Vita but also PSVSD....and of course I got stuff spread out all over the place:
PSVSD = Apps + Vita games
SD2Vita = PSP + Retro Games
RetroFlow currently has no issues with getting at my PSP stuff (YaY!)....but Retro Games is a different story at present...with them being on a different drive than the App.

This is something I'm sure I can edit the code to allow in a hackish way.

(Suggestion) Maybe add a bind to Square-Button to swap between mount points & refresh directory list @ root level.

**Comment by jimbob4000** [comment]
So retro and psp are okay, but vita apps aren't found?

I don't have a 3G model so not sure if I will be able to test and add this.

**Comment by GrindLogic** [comment]
Okay I wasn't clear enough, sorry about that...Apps & Vita are fine, as is PSP/PS1 eboot; It's only Retro that is giving me grief.

ux0 = PSVSD = Apps + Vita Games
uma0 = SD2Vita = PSP + Retro Games

Yes most folks have the SD2Vita mounted as ux0...but since the SD2Vita is far more accessible than the PSVSD...I swapped them around....honestly I should probably mounted SD2Vita as grw0..since it's in the game slot...but oh well.

I found and edited 'rom_directories.lua' but clearly I made a mistake...as I got the error...I'll fix it or roll back to v4.00 as recommended.

I'm not sure a 3G model is needed, but would most certainly help to remove all doubts. When I get some free funds I'll contact you for your snail mail address and fire off a 3G your way.

VitaShell has code in it to directly access the drives...this is in it's USB connection settings. However this just dumbs things down for folks like me that forget what they mounted the drive as. :)

VitaShell:
sd2vita \ psvsd \ Memory Card \ Game Card

If one can just cycle through the mount points:
os0: Core OS Files
pd0: Welcome Park App
sa0: Fonts & Dictionaries
tm0: NpDRM/DevKit
ud0: System Updates
uma0: USB Port
ur0: User Data (LiveArea Layout)
ux0: Sony Memory Card
vd0: Settings
vs0: Default Apps
imc0: Vita 2K Storage
gro0: Game (Read-Only)
grw0: Game (Read-Write)

However I think the only ones, one can (safely) mount and put data on are: 
uma0
ux0 - Digital Vita games only work here
grw0
imc0 - physical storage on 2K models 

Really the first three are the common options for SD2Vita \ PSVSD mounting points.

Thanks for getting back to me, and it goes without saying thanks for all the effort you have put into RetroFlow.

**Comment by jimbob4000** [comment]
Thanks for the extra info. 

I appreciate the snail mail option, but it's not necessary. 

I'll need to investigate a bit further. 

The file manager is a bit dumb, for the time being editing the rom directory lua may be the best option, I'll try a uma0 directory over the weekend to see if it works for me.

**Comment by GrindLogic** [comment]
No problem, always looking to help solve a problem I created. ;)

Snail is likely a month or two away...a 3G is like $120 a PSVSD is like $25...so with likely shipping that's what $160 total...and programmers make what $80 an hour....so if I rope you into more than 2 hours worth of work I'm coming out ahead. :)

RetroArch for Vita hunts for game assets in:
app0 \ ur0 \ ux0 \ uma0 \ imc0

I've heard of app0 but never seen it...and it's certainly not on my 3G...and never heard of it being used as a mount point for SD2Vita or PSVSD.

The error I got from my edits to the lua file were indeed do to missing folders...so added the missing folders and things are fine.

*Side Note* CHD image support works fine for NEC TurboGrafx CD \ PC Engine CD and Sega CD...SNK NeoGeo CD "might" work with an OC Vita...but at default clocks it fails.

**Comment by jimbob4000** [comment]
Hi, I think I've added the bits you wanted.

I've added rom directory support for uma0, imc0, xmc0, grw0 partitions.
(App0 is a virtual partition for the app that's currently open, so no need for that one).

Chd extension support has been added for Sega CD, TurboGrafx-CD and PC Engine CD.
Neo-Geo CD doesn't run well, so I've left that system out.

You can try it out in the updated the pre-release:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v4.0.1

Thanks for your comments, I think it's helped improve the app.

**Comment by GrindLogic** [comment]
Looks really good. :)

This is a major boon for those of us that have odd ball setups. :)

I completely missed xmc0....good catch.

Suggestion or two...under "Scan Settings" dialog rename "Rescan" to "Rescan All"....dependent on the following suggestion.

Then under "edit game directories...\Game directories" dialog rename "Rescan" to "Rescan Active" and edit the behavior to only scanning the active directory. This I imagine, would cut down on time spent scanning for assets...if a user has only added one new system....or like changed assets from ISO to CHD...if that makes a difference at all.

Thanks for the effort.

**Comment by jimbob4000** [comment]
Thanks, glad you like it. 

I think I'll leave the scan behaviour alone, it gets messy scanning just and edited system, people may change more than one at a time and it could be missed. 

Once setup, people shouldn't have to edit too much.

**Comment by GrindLogic** [comment]
Oh nothing is idiot proof...because just when you think you have made it so...the world creates an even more confounding idiot.

I largely agree with you...but as someone that has 2 1tb microSD's in their Vita....repeated scans can be mind numbing.

hmm speaking of mind numbing scans...I'm fairly sure it was GBA that the scan picked up some SaveStates that were in the rom folder for whatever reason, that created duplicates in RetroFlow.

The file extensions that picked up as games were *.sav & *.ss0

**Comment by jimbob4000** [comment]
There's probably more save extensions to filter out, I think these are the main ones. 

sav, srm, mpk, eep, st0, sta, sr0, ss0. 

I'll see what sort of affect it has on scanning times and decide from there.

**Comment by jimbob4000** [comment]
@GrindLogic , it didn't affect loading times.
I've added filters to exclude save files and updated the pre-release.
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v4.0.1

Thanks for highlighting

**Comment by GrindLogic** [comment]
Oh good deal, and thanks for the update.
