### ISSUE TITLE
Added cover for Slenderman Homebrew STEP62012

### ISSUE THREAD

**Issue by SoulEaterGames** [jimbob4000/RetroFlow-Launcher#78]
![D78895BF-468F-4A22-8EB4-288D94E6E5D2](https://user-images.githubusercontent.com/11793487/192867122-7e7a7b25-4afc-42a3-84b9-7e63920c29a1.png)

**Comment by jimbob4000** [comment]
Awesome, thanks for sharing, I've added it to the cover repo.
