### ISSUE TITLE
Error on scanning when a file has no extension

### ISSUE THREAD

**Issue by thipeto** [jimbob4000/RetroFlow-Launcher#80]
Checking error when a file has no extension

It gives an error when it occurs. Is it possible for the application to handle the error, or at least inform the user? I just found out by accident

These are "Amiga - Commodore" rom files

![commodore_error](https://user-images.githubusercontent.com/81275215/193376693-840890f9-066b-47c2-bc59-942b1391d5ad.jpg)

**Comment by jimbob4000** [comment]
Thanks for letting me know.
The issue has been fixed in the pre-release version:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/4.0.2
