### ISSUE TITLE
C64 cover download stuck

### ISSUE THREAD

**Issue by alfchk** [jimbob4000/RetroFlow-Launcher#81]
Hi

Everytime i close retroflow turbo graph cd disappear.

If I try to download artwork for commodore 64, that stuck on "1 find" for covers and on "0 find" for background.

If I try download all artworks that stuck After ~6000.

And since 4.0.3 artworks dont Always appear After download and refresh.

**Comment by jimbob4000** [comment]
Hi

I've found the issue with tgcd and will fix shortly. 

C64 covers and backgrounds appear to be working fine. 

6,000+ games is a lot. 
Try to download category by category instead.

**Comment by alfchk** [comment]
Hi
Big thanks for you fast response.
Catégory by catégory for commodore stuck on the first one.
Do you have a PayPal account for a little tips? :)
________________________________
De : jimbob4000 ***@***.***>
Envoyé : mardi 25 octobre 2022 17:29
À : jimbob4000/RetroFlow-Launcher ***@***.***>
Cc : alfchk ***@***.***>; Author ***@***.***>
Objet : Re: [jimbob4000/RetroFlow-Launcher] Few issue (Issue #81)


Hi

I've found the issue with tgcd and will fix shortly.

C64 covers and backgrounds appear to be working fine.

6,000+ games is a lot.
Try to download category by category instead.

**Comment by jimbob4000** [comment]
Thanks for the offer, no tips necessary. 

If you can send me the following file I will try and replicate the problem. 

"ux0:/data/RetroFlow/CACHE/db_c64.lua"

You can upload to wetransfer, Google drive or something similar and I will remove the link from the comment once I have the file.

**Comment by jimbob4000** [comment]
TurboGrafx CD has been fixed in the updated pre-release:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v4.03

**Comment by alfchk** [comment]
Big thanks
I have made two vidéo when i try to download artworks for c64:
https://streamable.com/umyd9z
https://streamable.com/81sl2c

And the LUA:
Http://Shorturl.at/aeGVW

Thanks again for your precious time


________________________________
De : jimbob4000 ***@***.***>
Envoyé : mardi 25 octobre 2022 19:28
À : jimbob4000/RetroFlow-Launcher ***@***.***>
Cc : alfchk ***@***.***>; Author ***@***.***>
Objet : Re: [jimbob4000/RetroFlow-Launcher] C64 cover download stuck (Issue #81)


TurboGrafx CD has been fixed in the updated pre-release:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v4.03

**Comment by jimbob4000** [comment]
Thanks for the file and videos, much appreciated.
It may take a while to track down the issue, I'll keep you posted

**Comment by alfchk** [comment]
On your updated 4.0.3
For c64 artworks download, for covers that stuck immediatly when i click. No popup Windows open.
For background no change, that stuck on "find 0"
________________________________
De : jimbob4000 ***@***.***>
Envoyé : mardi 25 octobre 2022 18:23
À : jimbob4000/RetroFlow-Launcher ***@***.***>
Cc : alfchk ***@***.***>; Author ***@***.***>
Objet : Re: [jimbob4000/RetroFlow-Launcher] Few issue (Issue #81)


Thanks for the offer, no tips necessary.

If you can send me the following file I will try and replicate the problem.

"ux0:/data/RetroFlow/CACHE/db_c64.lua"

You can upload to wetransfer, Google drive or something similar and I will remove the link from the comment once I have the file.

**Comment by alfchk** [comment]
Thanks
________________________________
De : jimbob4000 ***@***.***>
Envoyé : mardi 25 octobre 2022 22:22
À : jimbob4000/RetroFlow-Launcher ***@***.***>
Cc : alfchk ***@***.***>; Author ***@***.***>
Objet : Re: [jimbob4000/RetroFlow-Launcher] C64 cover download stuck (Issue #81)


Thanks for the file and videos, much appreciated.
It may take a while to track down the issue, I'll keep you posted

**Comment by jimbob4000** [comment]
It seems to be an issue wih game files that contain a "%" symbol in the filename.
Try removing those files to see if it works.

I may need to remove those games if I can't find a better solution.

**Comment by alfchk** [comment]
Hi
I delete % character and it work. Thanks.
But a problem remain. Artworks dont appears After download and refresh.
(I have try to download by category and download all but same result. Covers are in the directory but doesnt appears. And when i download one by one in retroflow covers appear immediatly)

**Comment by alfchk** [comment]
Background appear when refresh but not the covers

**Comment by jimbob4000** [comment]
Hi, is it for c64?

Can you point me towards an example filename?
I have the list from before.

It may take me a few days to get round to a fix.

Thanks

**Comment by alfchk** [comment]
I have tried to delete cache, background and cover directory, rescan all, download all and refresh, backgrounds are ok but non covers (they arein thé derectory but dont appears when refresh. I have tried download all and refresh and download by category and refresh but without success)

**Comment by jimbob4000** [comment]
Okay, can you give me the filenames for some of the games and let me know which system they are for so I can test please?

Are any covers showing?
It may be that some covers aren't available to download.

**Comment by alfchk** [comment]
No one games cover. If I download one by one it work. But by category or all dont work
________________________________
De : jimbob4000 ***@***.***>
Envoyé : vendredi 28 octobre 2022 10:55
À : jimbob4000/RetroFlow-Launcher ***@***.***>
Cc : alfchk ***@***.***>; Author ***@***.***>
Objet : Re: [jimbob4000/RetroFlow-Launcher] C64 cover download stuck (Issue #81)


Okay, can you give me the filenames for some of the games and let me know which system they are for so I can test please?

Are any covers showing?
It may be that some covers aren't available to download.

**Comment by alfchk** [comment]
I sent you lua files later this day
________________________________
De : jimbob4000 ***@***.***>
Envoyé : vendredi 28 octobre 2022 10:55
À : jimbob4000/RetroFlow-Launcher ***@***.***>
Cc : alfchk ***@***.***>; Author ***@***.***>
Objet : Re: [jimbob4000/RetroFlow-Launcher] C64 cover download stuck (Issue #81)


Okay, can you give me the filenames for some of the games and let me know which system they are for so I can test please?

Are any covers showing?
It may be that some covers aren't available to download.

**Comment by alfchk** [comment]
All the cache directory:
Http://shorturl.at/alvz1

________________________________
De : jimbob4000 ***@***.***>
Envoyé : vendredi 28 octobre 2022 10:55
À : jimbob4000/RetroFlow-Launcher ***@***.***>
Cc : alfchk ***@***.***>; Author ***@***.***>
Objet : Re: [jimbob4000/RetroFlow-Launcher] C64 cover download stuck (Issue #81)


Okay, can you give me the filenames for some of the games and let me know which system they are for so I can test please?

Are any covers showing?
It may be that some covers aren't available to download.

**Comment by jimbob4000** [comment]
Thanks, the link doesn't work, but I've updated pre-release 4.0.3 to try and fix the issue.

Please download and install it again to see if it fixes the issue
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v4.03


If it still doesn't after installing the version above then please send me a video and the files below.
Also send the files below.

- config.dat
- rom_directories.lua
- cache folder (and all lua files inside)

Thanks

**Comment by alfchk** [comment]
It work!
But...
Manually added cover dont appears. (Theses covers are shown before)
________________________________
De : jimbob4000 ***@***.***>
Envoyé : samedi 29 octobre 2022 11:56
À : jimbob4000/RetroFlow-Launcher ***@***.***>
Cc : alfchk ***@***.***>; Author ***@***.***>
Objet : Re: [jimbob4000/RetroFlow-Launcher] C64 cover download stuck (Issue #81)


Thanks, the link doesn't work, but I've updated pre-release 4.0.3 to try and fix the issue.

Please download and install it again to see if it fixes the issue
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v4.03

If it still doesn't after installing the version above then please send me a video and the files below.
Also send the files below.

  *   config.dat
  *   rom_directories.lua
  *   cache folder (and all lua files inside)

Thanks

**Comment by jimbob4000** [comment]
Use the rescan or 'Rafraîchir' button and the custom covers should appear.

**Comment by alfchk** [comment]
It work!!!
Thanks
________________________________
De : jimbob4000 ***@***.***>
Envoyé : dimanche 30 octobre 2022 00:02
À : jimbob4000/RetroFlow-Launcher ***@***.***>
Cc : alfchk ***@***.***>; Author ***@***.***>
Objet : Re: [jimbob4000/RetroFlow-Launcher] C64 cover download stuck (Issue #81)


Use the rescan or 'Rafraîchir' button and the custom covers should appear.
