### ISSUE TITLE
Mass Effect Infiltrator Cover

### ISSUE THREAD

**Issue by SoulEaterGames** [jimbob4000/RetroFlow-Launcher#84]
![8F5FDC93-E31A-460F-8AD2-A1ECE0EC0BFC](https://user-images.githubusercontent.com/11793487/201560103-e4daea60-1639-4ec8-b379-52bab6ee40c7.jpeg)

**Comment by jimbob4000** [comment]
Thanks for the cover. 

Unfortunately I don't think I can add it until it's been ported. 

Hopefully someone will take on your bounty soon 👍

**Comment by SoulEaterGames** [comment]
@jimbob4000 can you reopen? The port was released today

**Comment by jimbob4000** [comment]
Hi, I've added it to the repo: https://github.com/jimbob4000/hexflow-covers/blob/main/Covers/PSVita/MASSEFFEC.png

Thanks again
