### ISSUE TITLE
Retro Roms cover arts are not being downloaded/shown

### ISSUE THREAD

**Issue by Husky363** [jimbob4000/RetroFlow-Launcher#94]
so my roms for the GBC/GBA and etc..are launching with no issues however, whenever i try to download the covers it doesnt appear. even though some of the games are not being detected and those that gets detected the cover arts gets downloaded but still doesnt show up on the flow launcher

**Comment by jimbob4000** [comment]
Try rescanning. 

Covers should show if they have been downloaded.

**Comment by Husky363** [comment]
> Try rescanning.
> 
> Covers should show if they have been downloaded.

thank you very much for your reply. i have figured out the issue i was having. the name format of the game is not as no intro as you have mentioned in the FAQ it was missing the region code at the end of each rom. you may close this incident as its not considered as an issue

**Comment by jimbob4000** [comment]
No problem, glad you figured out the issue.
