### ISSUE TITLE
Feature request: Add FBA CPS1, CPS2 cores. Merge FBA cores into one category and Mame cores into one category

### ISSUE THREAD

**Issue by John3d** [jimbob4000/RetroFlow-Launcher#95]
I'm not sure if this is considered a problem, but in the category for the FBA emulator the core fba_2012 has been assigned, however some games run with better performance if they are separated by system or boards (like Neo Geo which has its own category with the core fba_2012_neogeo) and there should be an option to run CPS1 and CPS2 games with the separate core they have.
Would it be possible? 

Thanks.

**Comment by jimbob4000** [comment]
Hi, I think this is more of a feature request. 

Can you clarify a bit more please, are there additional cores you would like added?

Plus an option to merge them into which categories?

Thanks

**Comment by John3d** [comment]
Ok, I'll try to explain myself a bit better. 

Plus an option to merge them into which categories.

In the case of the PS Vita, I don't have that much experience and maybe I should apologise if it's not the same (I haven't tried many games on the FB ALPHA 2012 yet)

In the case of some consoles like Wii, the FB Alpha 2012 core has been compiled separately in different cores depending on the arcade board that the games use and thus gain performance on some arcade boards. On Retroarch PSVita, it is officially as follows:
FB Alpha 2012 (includes NeoGeo, Cps1, Cps2, etc.)
But there is a version of this core that only emulates NeoGeo, another one that only emulates CPS1 and another one that emulates CPS2.
In short, 4 cores where the first one encompasses the other 3 among other systems:
FB ALPHA 2012
     ----- FB ALPHA 2012 Neo Geo 
     ----- FB ALPHA 2012 CPS1
     ----- FB ALPHA 2012 CPS2

But in Wii, for example, the official version are those same cores but there are other unofficial ones that allow to emulate better boards that in the base core are slower:
FB ALPHA 2012
     ----- FB ALPHA 2012 Neo Geo 
     ----- FB ALPHA 2012 CPS1
     ----- FB ALPHA 2012 CPS2
     ----- FB ALPHA 2012 CPS3
     ----- FB ALPHA 2012 PGM
     ----- FB ALPHA 2012 CAVE
     ....
  I, for one, have made a habit of using the board specific core whenever possible to ensure better performance.
  In short, I think that in view of the new cores that are segments of the FB ALPHA 2012, it would be beneficial to be able to assign different cores to the same category. Since right now (in the absence of testing the performance of all CPS2 games on the base core) it is a problem to be able to play this system optimally.
The same reasoning would work for other systems like mame 2003 (which also has several subcores in wii) or systems where some games need a specific emulator to work properly.

Sorry for the inconvenience.

**Comment by jimbob4000** [comment]
Thanks for the extra info, it makes more sense.

There's quite a lot of code to change to add the extra cores and merge the four fba cores into one category and also the two name cores into one category.

There's no core override in retroflow, so they would need to be separated manually into folders for the cores.
If it's added I would probably still keep neo-geo as a separate category (games could be added in either an FBA folder or a neo-geo folder).

I might have a look at it in the new year when I've got more time, but not sure if it will be added.

**Comment by John3d** [comment]
Thanks for considering these changes, although if it requires a lot of work and there is no time to add them don't worry because you have already done a great job with the launcher.

Neogeo, as you mentioned, I also consider that it should have its own category because it is an arcade board but also a console. That's fine as well.

Maybe a simpler solution to implement would be to consider the CPS1 and CPS2 systems as separate systems in their own category. If someone doesn't want these categories to appear, just leave the corresponding folders empty, right?

Anyway, thanks for your attention and whatever decision you make I accept it, as I said before the important work is done in making this launcher.

Thanks for everything
