### ISSUE TITLE
Renaming Vita Games messes some things

### ISSUE THREAD

**Issue by Nerago-Fikuxu** [jimbob4000/RetroFlow-Launcher#96]
Hey there, I've had problems when I tried to rename Vita games, for example I was renaming Catherine Full Body which was written in kanjis, when I clicked done after renaming it the screen froze on the game on the right side of Catherine(which was The Liar Princess and the Blind Prince but also written in kanjis) and when the app unfroze the game "The Liar Princess and the Blind Prince" was actually the one that was renamed with "Catherine Full Body" and the real Catherine Full Body vanished from Vita category, I managed to find out it got placed on the Homebrew category for some reason and its name was still written in kanjis as if I didn't rename it.
Has any one experienced this kind of issue ?
Tested on a Playstation TV, running on 3.65 Enso

**Comment by jimbob4000** [comment]
Hi, did the new name you typed include kanjis characters or just Latin?

Does renaming Latin (western) games work ok for you?

Thanks

**Comment by jimbob4000** [comment]
I can't seem to replicate the issue. 

It appears to be working on the pre-release version:

https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v5.0.2

Try updating the this version of the app to see if it helps.

**Comment by Nerago-Fikuxu** [comment]
I tried the pre-release version and indeed it does not have that issue anymore.
Thanks for your help!
