### ISSUE TITLE
Scan option still run when launching Retroflow even if the option is disactivated

### ISSUE THREAD

**Issue by th3on301** [jimbob4000/RetroFlow-Launcher#97]
Hello! First of all I want to thank you and the team for the work! I have installed the latest version (5.0.1) and after the first scanning of the games, I disactivated the option from the menu but when starting again RetroFlow it's scanning again all the games and takes too much time. Is it possible to check the option, please? Many thanks!

**Comment by jimbob4000** [comment]
Hi. 

Maybe the cached files haven't fully saved. 

Try turning off the startup scan and waiting a minute before closing the app. 

You could also try this prerelease version. 

https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v5.0.2

If it's still not working, try deleting the cache and titles folder in the retroflow data folder. 

The config file could also be deleted and it will default to turning off the startup scan.

**Comment by th3on301** [comment]
Hello! I have followed your instructions and installed the pre-release version but the issue was still persisting so I have tried to change the scan option to 0 inside the config.dat file manually and looks like is working fine now. Thank you!
