### ISSUE TITLE
Garbled Japanese Titles

### ISSUE THREAD

**Issue by kazum1kun** [jimbob4000/RetroFlow-Launcher#98]
Hello,

I upgraded the launcher from 4.x to the latest 5.0.2 version and I noticed all Japanese (hiragana/katakana) titles are not displaying correctly. Chinese (kanji) texts seems to be fine. I think 4.x versions did not have this issue. 

Thank you!

**Comment by jimbob4000** [comment]
Hi, is it just for PSP and PlayStation 1 titles? Or Vita game titles too?

Trying to figure out if the font is the problem, or the title scanning. 

Thanks

**Comment by kazum1kun** [comment]
Both PSP and PSV titles. I don't have PSX titles so I can't test.

**Comment by jimbob4000** [comment]
Okay, what language are you using in the app?

Also do the app titles look correct when the language is changed to English?

Thanks

**Comment by kazum1kun** [comment]
I'm using it in English. I tried to switch it to Japan but it has the same garbled text.

Here are some pics with the garbled titles. It looks like an encoding/decoding issue (for example, "の" is consistently mapped to "ã").

https://i.imgur.com/RsjbE1w.jpg
https://i.imgur.com/3V3PtsN.jpg
https://i.imgur.com/z0t7aQE.jpg

**Comment by jimbob4000** [comment]
Thanks for the photos, they were very helpful.

I've updated the pre-release to fix the issue, installing it should fix the problem.
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v5.0.2

I'll close the issue for now, but let me know if there's still a problem.

Thanks for your help.

**Comment by kazum1kun** [comment]
Thanks a lot. I can confirm that this issue was fixed. (A rescan was needed to correctly populate the names)
