### ISSUE TITLE
Option to Swap X and O buttons

### ISSUE THREAD

**Issue by kazum1kun** [jimbob4000/RetroFlow-Launcher#99]
Hello

It looks like the sound would randomly pop when I hold down left/right to continuously scroll the view. See https://photos.app.goo.gl/HaJKWspzAszVRUsK9 for a video.

Thank you!

Ps: unrelated but is there a chance to follow system settings for O/X bindings (or let users set it)? That would be a huge QoL for Asian countries and those who prefer it. Thanks again.

**Comment by jimbob4000** [comment]
Hi, I can add an option to swap the O and X buttons.
The sound issue is an old problem, with no solution yet.

**Comment by kazum1kun** [comment]
Thanks a lot 👍

**Comment by jimbob4000** [comment]
Hi again.

I've added the setting for swapping the X and O buttons, download the updated pre-release to try it out:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v5.0.2

You can swap the buttons by going to 'Settings > Theme > Swap X and O buttons'.
Let me know if there are any issues with the new feature.

Thanks

**Comment by kazum1kun** [comment]
Thanks, it works great, didn't notice any issue.
